import { AccessLevel, NetworkZone } from "@/app/generated/prisma/enums";
import type { ScenarioDefinition } from "./types";
import { dns, guidedOnboarding, service, withObjectiveHints } from "./content";

const learning = (
  concepts: string[],
  evidence: string,
  domain: "COMPUTING_OS" | "SECURITY_REASONING" = "COMPUTING_OS",
): NonNullable<ScenarioDefinition["objectives"][number]["learning"]> => ({
  domain,
  concepts,
  stage: "PRACTICED",
  evidence,
});

export const firstShift: ScenarioDefinition = {
  id: "first-shift",
  name: "First Shift",
  organization: "Nodeline Security",
  briefing: {
    red: "Complete a workstation handover using only information available on OPS-01. Record what the system proves about your session, its files, and its running services.",
    blue: "This orientation assignment has no defensive role.",
    constraints: ["Use the bounded ROOT/OS terminal", "Treat command output and local documentation as evidence", "Do not infer facts that the workstation has not shown"],
  },
  objectiveSummary: "Establish an evidence-backed workstation baseline",
  presentation: { caseId: "NDL-00", focus: ["Terminal fundamentals", "Operating systems", "Evidence"], order: 0 },
  availableModes: ["RED"],
  assistance: {
    guided: guidedOnboarding,
    operator: "Use the welcome file and workstation handbook as the only procedure. Record conclusions only when terminal output supports them.",
    operatorAvailableAtStart: true,
  },
  conditions: { timeLimitMinutes: 20, minimumAvailability: 100 },
  securityControls: [{ host: "OPS-01", telemetry: ["SYSTEM", "FILESYSTEM", "PROCESS"] }],
  businessServices: [{ name: "Operator documentation", hosts: ["OPS-01"], impact: "New operators cannot access local procedures." }],
  persistencePolicy: { process: "orientation-agent", requiredPrivilege: AccessLevel.ROOT, beaconSeconds: 60 },
  knowledgeRewards: [],
  backgroundActivity: [],
  dnsRecords: dns({ "ops-01.nodeline.test": "OPS-01" }),
  startingKnowledge: { knownHosts: ["OPS-01"], knownAssets: [] },
  startingSession: { host: "OPS-01", user: "trainee", path: "/home/trainee" },
  facts: [
    {
      id: "orientation.handbook",
      category: "HOST",
      known: "Local procedures distinguish observed evidence from untested assumptions.",
      unknown: "Where Nodeline keeps workstation procedures",
      guidance: "Follow the path published in WELCOME.txt, then inspect and read the handbook.",
      discoverableFrom: "/home/trainee/WELCOME.txt and /usr/share/doc/nodeline/FIRST_SHIFT.txt",
      requiredFor: "Evidence-based workstation handover",
    },
    {
      id: "orientation.serviceRelationship",
      category: "HOST",
      known: "nodeline-docs is a process providing a service on OPS-01 at 10.0.0.10:8080.",
      unknown: "How the documentation service relates to its process, host, address, and port",
      guidance: "Compare the process table with the terminology in the local handbook.",
      discoverableFrom: "ps output for nodeline-docs",
      requiredFor: "Explaining the IP / host / service relationship",
    },
  ],
  machines: [{
    hostname: "OPS-01",
    ip: "10.0.0.10",
    zone: NetworkZone.INTERNAL,
    os: "linux",
    users: [
      { username: "trainee", role: "operator_trainee", privilege: AccessLevel.USER, groups: ["trainees", "operations"] },
      { username: "lead", role: "shift_lead", privilege: AccessLevel.USER, groups: ["operations"] },
      { username: "docs", role: "documentation_service", privilege: AccessLevel.SERVICE, groups: ["docs"] },
      { username: "root", role: "administrator", privilege: AccessLevel.ROOT, groups: ["root"] },
    ],
    services: [service("http", 8080, "docs", [NetworkZone.INTERNAL])],
    files: [
      {
        path: "/home/trainee/WELCOME.txt",
        owner: "trainee",
        group: "trainees",
        permissions: "640",
        isSecret: false,
        contents: [
          "NODELINE OPERATOR HANDOVER",
          "",
          "Establish where this shell opened and which identity it uses.",
          "Inspect a long listing before reading files; ownership and permissions determine access.",
          "Local procedure: /usr/share/doc/nodeline/FIRST_SHIFT.txt",
          "Change to that directory, inspect it, and read the procedure.",
          "Finish by inspecting the process table and comparing it with the procedure.",
        ].join("\n"),
      },
      {
        path: "/usr/share/doc/nodeline/FIRST_SHIFT.txt",
        owner: "root",
        group: "trainees",
        permissions: "640",
        isSecret: false,
        contents: [
          "FIRST SHIFT // WORKSTATION EVIDENCE",
          "",
          "pwd reports the shell's current directory. whoami reports the current username.",
          "id adds numeric identity and group membership. env reports inherited session context.",
          "A long listing records permission digits, owner, group, and path. Read access is evidence; a filename alone is not.",
          "ps reports running processes. A service is behavior a process provides to other software or users.",
          "OPS-01 is a hostname: a stable machine name. 10.0.0.10 is its interface address.",
          "The nodeline-docs process provides the documentation service at 10.0.0.10:8080; 8080 identifies the listening endpoint.",
          "State conclusions from observed output. Mark everything else as an assumption to test.",
        ].join("\n"),
      },
      {
        path: "/srv/briefing/shift-notes.txt",
        owner: "lead",
        group: "operations",
        permissions: "640",
        isSecret: false,
        contents: "Shift note: documentation service expected on OPS-01. Confirm from process evidence before reporting it healthy.",
      },
    ],
    processes: [
      { name: "sshd", pid: 184, runningAs: "root", commandLine: "/usr/sbin/sshd -D" },
      { name: "nodeline-docs", pid: 412, runningAs: "docs", commandLine: "/usr/local/bin/nodeline-docs --listen 10.0.0.10:8080 --root /usr/share/doc/nodeline" },
    ],
  }],
  connections: [],
  discoveries: [
    { trigger: { kind: "file", host: "OPS-01", value: "/usr/share/doc/nodeline/FIRST_SHIFT.txt" }, facts: ["orientation.handbook"] },
    { trigger: { kind: "process", host: "OPS-01", value: "nodeline-docs" }, facts: ["orientation.serviceRelationship"] },
  ],
  objectives: withObjectiveHints("first-shift", [
    { id: "locate-session", type: "event", label: "Establish the current directory", event: { action: "OBSERVATION_RECORDED", targetHost: "OPS-01", metadata: { kind: "CURRENT_DIRECTORY" } }, learning: learning(["Files and directories", "Command-line navigation"], "Observed the active shell working directory with pwd.") },
    { id: "identify-user", type: "event", label: "Identify the current user", event: { action: "OBSERVATION_RECORDED", targetHost: "OPS-01", metadata: { kind: "CURRENT_USER" } }, learning: learning(["Users"], "Observed the session username with whoami.") },
    { id: "inspect-groups", type: "event", label: "Inspect identity and group membership", event: { action: "OBSERVATION_RECORDED", targetHost: "OPS-01", metadata: { kind: "IDENTITY_GROUPS" } }, learning: learning(["Users and groups", "Permissions"], "Observed identity, privilege, and group membership with id.") },
    { id: "inspect-environment", type: "event", label: "Inspect the session environment", event: { action: "OBSERVATION_RECORDED", targetHost: "OPS-01", metadata: { kind: "ENVIRONMENT" } }, learning: learning(["Environment variables", "Current host"], "Observed host and session context through environment variables.") },
    { id: "inspect-permissions", type: "event", label: "Inspect file ownership and permissions", event: { action: "OBSERVATION_RECORDED", targetHost: "OPS-01", metadata: { kind: "DIRECTORY_LISTING", detailed: true } }, learning: learning(["Files and directories", "Permissions"], "Used a long directory listing to observe owner, group, permissions, and path.") },
    { id: "navigate-docs", type: "event", label: "Navigate to local documentation", event: { action: "OBSERVATION_RECORDED", targetHost: "OPS-01", metadata: { kind: "DIRECTORY_CHANGED" } }, learning: learning(["Command-line navigation", "Documentation"], "Changed the shell working directory using an in-world documented path.") },
    { id: "read-handbook", type: "fact", factId: "orientation.handbook", label: "Read the workstation evidence procedure", learning: learning(["Documentation", "Evidence versus assumptions"], "Read the local procedure and recorded its evidence rule.", "SECURITY_REASONING") },
    { id: "inspect-services", type: "fact", factId: "orientation.serviceRelationship", label: "Relate a process to its host and service", learning: learning(["Processes", "Services", "IP / host / service relationship"], "Correlated the process command line with the documented host, address, port, and service.") },
  ]),
  objectiveCompletion: "ALL",
  beginnerExitQuestions: [
    { id: "current-host", prompt: "What host are you operating, and what evidence establishes it?", evidenceObjectives: ["inspect-environment"] },
    { id: "current-user", prompt: "Which user and groups define this session?", evidenceObjectives: ["identify-user", "inspect-groups"] },
    { id: "files-permissions", prompt: "What do the file owner, group, and permission digits say about access?", evidenceObjectives: ["inspect-permissions", "read-handbook"] },
    { id: "processes", prompt: "Which process provides the documentation service, and who runs it?", evidenceObjectives: ["inspect-services"] },
    { id: "host-service", prompt: "How do OPS-01, 10.0.0.10, nodeline-docs, and port 8080 relate?", evidenceObjectives: ["inspect-environment", "inspect-services"] },
  ],
  detections: {},
  routes: [],
  blueProfiles: [],
  defaultBlueProfile: "",
};
