import type { ScenarioDefinition } from "./types";
import { commonDetections, discover, external, file, host, identity, link, route } from "./content";

export const ghostAccount: ScenarioDefinition = {
  id: "ghost-account", name: "Operation Ghost Account", organization: "Northline Health",
  presentation: { caseId: "IR-18", order: 9, prerequisite: "something-calling-home", focus: ["Authorization", "Persistence", "Recovery"] },
  briefing: { red: "A dormant provisioning account and a privileged intake worker both lead to the credential recovery register. Retrieve RECOVERY_CODES.csv and maintain access if possible.", blue: "A supposedly retired account has resumed activity alongside unusual intake processing. Remove the unauthorized access without locking out legitimate recovery workflows.", constraints: ["Disabling every recovery identity would interrupt patient access recovery", "Session revocation alone does not remove persistent access"] },
  availableModes: ["RED", "BLUE"], assistance: { guided: ["The provisioning account is a valid identity with an invalid lifecycle state.", "The intake worker can sustain a beacon after its original session is revoked.", "Compare an identity response with removing the persistence it left behind."], operator: "Use authorization state, process evidence, and recovery-business context to distinguish a ghost account from valid emergency access." },
  conditions: { timeLimitMinutes: 90, minimumAvailability: 60 }, aliases: { "intake.northline.test": "INTAKE-WEB" }, startingKnowledge: { knownHosts: ["INTERNET", "INTAKE-WEB"], knownAssets: ["intake.northline.test"] },
  machines: [external, host("INTAKE-WEB", "10.81.1.10", "DMZ", [identity("root", "ROOT")], [file("/etc/intake/recovery.conf", "root", "RECOVERY_HOST=RECOVERY-01\nUSER=recovery_svc\nTOKEN=northline-recovery")], true), host("PROVISION-01", "10.81.1.30", "DMZ", [identity("emergency_admin")], [file("/home/emergency_admin/status.txt", "emergency_admin", "Provisioning account retired after migration. Legacy recovery access remains on RECOVERY-01 as recovery_svc.")]), host("RECOVERY-01", "10.81.2.10", "INTERNAL", [identity("recovery_svc", "SERVICE")], [file("/srv/recovery/RECOVERY_CODES.csv", "recovery_svc", "SIMULATED RECOVERY REGISTER\ncohort,code\nnight,redacted")]), host("IDENTITY-01", "10.81.2.30", "INTERNAL", [identity("identity_svc", "SERVICE")])],
  connections: [link("INTERNET", "INTAKE-WEB", 443), link("INTERNET", "PROVISION-01", 22, "GHOST_ACCOUNT_LOGIN"), link("INTAKE-WEB", "RECOVERY-01", 22, "INTAKE_RECOVERY_LOGIN"), link("PROVISION-01", "RECOVERY-01", 22, "GHOST_RECOVERY_LOGIN"), link("IDENTITY-01", "RECOVERY-01", 22)],
  discoveries: [{ trigger: { kind: "web", host: "INTAKE-WEB", value: "intake.northline.test" }, output: "Northline intake service\nLegacy provisioning: emergency_admin@PROVISION-01 / EmergencyProvision-9\nRecovery reconciliation worker enabled.", hosts: ["PROVISION-01"], credentials: [{ username: "emergency_admin", scope: "PROVISION-01" }] }, discover("INTAKE-WEB", "/etc/intake/recovery.conf", "RECOVERY-01", "recovery_svc"), discover("PROVISION-01", "/home/emergency_admin/status.txt", "RECOVERY-01", "recovery_svc")],
  webInteractions: [{ host: "INTAKE-WEB", method: "POST", path: "/intake/reconcile", dataIncludes: "import=external", sessionUser: "root", prerequisiteAction: "PORT_PROBE", output: "The recovery reconciliation worker accepted the external import as root. Session opened.", evidence: [{ action: "WEB_WORKER_EXECUTED", category: "WEB", severity: "HIGH" }, { action: "PROCESS_SPAWN", category: "PROCESS", severity: "HIGH" }] }], objectives: [{ id: "recovery-codes", type: "retrieve_file", host: "RECOVERY-01", path: "/srv/recovery/RECOVERY_CODES.csv", label: "Retrieve RECOVERY_CODES.csv" }],
  detections: { ...commonDetections, GHOST_ACCOUNT_LOGIN: { id: "AUTH-GHOST-01", title: "Retired provisioning account used", severity: "HIGH", rationale: "The identity is valid in the directory but its lifecycle state does not permit remote use." }, INTAKE_RECOVERY_LOGIN: { id: "AUTH-INTAKE-01", title: "Intake worker reached recovery", severity: "MEDIUM", rationale: "A public intake service opened an interactive recovery session." }, GHOST_RECOVERY_LOGIN: { id: "AUTH-GHOST-02", title: "Retired account reached recovery", severity: "CRITICAL", rationale: "A retired provisioning path accessed sensitive recovery material." } },
  routes: [route("intake-persistence", "Intake persistence", ["INTERNET", "INTAKE-WEB", "RECOVERY-01"], "A root intake worker holds the recovery credential and can establish persistent access.", "Did a public intake worker establish a durable recovery route?", true), route("retired-provisioning", "Retired provisioning", ["INTERNET", "PROVISION-01", "RECOVERY-01"], "A dormant but valid provisioning account retains a recovery relationship after retirement.", "Did a retired identity retain authorization into recovery?", false)],
  blueProfiles: [{ id: "intake-persistence", routeId: "intake-persistence", commands: ["nmap INTAKE-WEB", "curl -X POST intake.northline.test/intake/reconcile --data import=external", "install-agent", "cat /etc/intake/recovery.conf", "ssh recovery_svc@RECOVERY-01", "retrieve RECOVERY_CODES.csv"] }, { id: "retired-provisioning", routeId: "retired-provisioning", commands: ["curl intake.northline.test", "ssh emergency_admin@PROVISION-01", "cat /home/emergency_admin/status.txt", "ssh recovery_svc@RECOVERY-01", "retrieve RECOVERY_CODES.csv"] }], defaultBlueProfile: "retired-provisioning",
  securityControls: [{ host: "INTAKE-WEB", telemetry: ["WEB", "PROCESS", "PERSISTENCE", "AUTH"] }, { host: "PROVISION-01", telemetry: ["AUTH", "NETWORK"] }, { host: "RECOVERY-01", telemetry: ["AUTH", "FILESYSTEM"] }], businessServices: [{ name: "Patient intake", hosts: ["INTAKE-WEB"], impact: "New patient intake is delayed." }, { name: "Account recovery", hosts: ["RECOVERY-01"], impact: "Patients cannot recover access." }, { name: "Identity synchronization", hosts: ["IDENTITY-01"], impact: "Identity changes are delayed." }], persistencePolicy: { process: "intake-health-agent", requiredPrivilege: "ROOT", beaconSeconds: 30 }, knowledgeRewards: [{ concept: "Authorization", actions: ["GHOST_ACCOUNT_LOGIN", "GHOST_RECOVERY_LOGIN", "INSPECT_USER"] }, { concept: "Persistence", actions: ["PERSISTENCE_INSTALLED", "REMOVE_PERSISTENCE"] }, { concept: "Incident response", actions: ["ATTACK_CONTAINED"] }], backgroundActivity: [{ host: "RECOVERY-01", source: "IDENTITY-01", user: "recovery_svc", action: "AUTH_SUCCESS", context: "Approved identity synchronization; recovery codes are never interactively exported." }],
};
