import { AccessLevel, NetworkZone, SecurityEventCategory, SecurityEventSeverity } from "@/app/generated/prisma/enums";
import type { ScenarioDefinition } from "./types";
import { service } from "./content";

const event = (
  action: string,
  category: SecurityEventCategory,
  severity: SecurityEventSeverity,
  options: { visibleToRed?: boolean; visibleToBlue?: boolean; metadata?: Record<string, unknown> } = {},
) => ({ action, category, severity, ...options });

export const glasshouse: ScenarioDefinition = {
  id: "glasshouse",
  name: "Operation Glasshouse",
  organization: "Meridian Dynamics",
  briefing: { red: "Assess the public portal and remote access relationships. Retrieve the protected finance document without modifying production data.", blue: "Investigate unusual application execution and remote access. Prevent finance extraction while preserving the portal and backup services.", constraints: ["Do not modify financial records", "Contain precisely and restore affected services"] },
  presentation: { caseId: "FIN-06", focus: ["Fundamentals", "Privilege escalation", "Finance trust"], order: 1, prerequisite: "first-shift" },
  availableModes: ["RED", "BLUE"],
  assistance: { guided: ["Start with the authorized public host. Use nmap to identify its services, then inspect any web service with curl. HTTP responses can reveal the application name or canonical hostname.", "Inspect pages before submitting anything. Forms publish their action, method, field names, and allowed values; linked profiles can reveal related systems without exposing a full solution.", "After gaining a session, use ls, cat, grep, less, and ps. A process's full command line often identifies the configuration file it loaded.", "PostgreSQL can be explored without knowing a database name in advance: connect with -h and -U, then use \\l, \\c, \\dt, and \\d before querying."], operator: "Follow the evidence across application, backup, and database trust boundaries." },
  conditions: { timeLimitMinutes: 90, minimumAvailability: 60 },
  securityControls: [{ host: "WEB-01", telemetry: ["WEB", "NETWORK", "PROCESS", "AUTH"] }, { host: "DEV-01", telemetry: ["AUTH", "NETWORK", "PRIVILEGE", "FILESYSTEM", "PERSISTENCE"] }, { host: "FIN-APP", telemetry: ["AUTH", "NETWORK"] }, { host: "VPN-01", telemetry: ["AUTH", "NETWORK"] }, { host: "BACKUP-01", telemetry: ["AUTH", "NETWORK"] }, { host: "FIN-DB", telemetry: ["AUTH", "FILESYSTEM"] }],
  businessServices: [{ name: "Employee portal", hosts: ["WEB-01"], impact: "Employees cannot access operations requests." }, { name: "Finance", hosts: ["FIN-APP", "FIN-DB"], impact: "Invoice processing stops." }, { name: "Backups", hosts: ["VPN-01", "BACKUP-01"], impact: "Scheduled recovery copies are delayed." }],
  persistencePolicy: { process: "root-agent", requiredPrivilege: AccessLevel.ROOT, beaconSeconds: 30 },
  knowledgeRewards: [{ concept: "Trust relationships", actions: ["LATERAL_MOVEMENT", "BACKUP_TRUST_LOGIN"] }, { concept: "Privilege escalation", actions: ["PRIVILEGE_ESCALATION"] }, { concept: "Incident response", actions: ["ATTACK_CONTAINED"] }],
  backgroundActivity: [{ host: "FIN-APP", user: "svc_web", action: "AUTH_SUCCESS", context: "Approved invoice application service account; scheduled processing." }],
  aliases: {
    "portal.meridian.test": "WEB-01",
    "vpn.meridian.test": "VPN-01",
    "fin-app.internal": "FIN-APP",
  },
  startingKnowledge: {
    knownHosts: ["INTERNET", "WEB-01"],
    knownAssets: [],
  },
  facts: [
    { id: "scope.webHost", category: "NETWORK", known: "Authorized host: WEB-01 (10.10.10.10)", unknown: "Public host services", knownAtStart: true, guidance: "Identify which services the authorized host exposes.", discoverableFrom: "Engagement scope", requiredFor: "Initial network investigation" },
    { id: "web.httpService", category: "NETWORK", known: "WEB-01 exposes HTTP on port 80", unknown: "Public web-service behavior", guidance: "Inspect the HTTP response with curl; headers and redirects can identify the application.", discoverableFrom: "nmap of WEB-01", requiredFor: "Application discovery" },
    { id: "portal.hostname", category: "APPLICATION", known: "Application hostname: portal.meridian.test", unknown: "Application hostname", guidance: "Request the canonical hostname and inspect the page it serves.", discoverableFrom: "HTTP redirect from 10.10.10.10", alternative: "Canonical-host response metadata", requiredFor: "Accessing the Meridian portal" },
    { id: "portal.profileEndpoint", category: "APPLICATION", known: "Published profile: /api/profile", unknown: "Published relationships", guidance: "Published profiles often describe supported remote-access relationships.", discoverableFrom: "Link on the portal page", requiredFor: "Discovering the backup-trust route" },
    { id: "portal.uploadEndpoint", category: "APPLICATION", known: "Legacy interface: /legacy-upload", unknown: "Portal interfaces", discoverableFrom: "HTML form action", requiredFor: "Testing the legacy upload worker" },
    { id: "portal.uploadMethod", category: "APPLICATION", known: "Legacy interface method: POST", unknown: "Legacy interface request shape", discoverableFrom: "HTML form method", requiredFor: "Testing the legacy upload worker" },
    { id: "portal.uploadField", category: "APPLICATION", known: "Legacy form field: upload", unknown: "Legacy interface request shape", discoverableFrom: "HTML select name", requiredFor: "Constructing a form request" },
    { id: "portal.uploadArchive", category: "APPLICATION", known: "Published upload value: archive", unknown: "Legacy interface request values", guidance: "Submit the form through an HTTP client using the published request shape.", discoverableFrom: "HTML option value", requiredFor: "Selecting the archive workflow" },
    { id: "vpn.relationship", category: "NETWORK", known: "Remote access host: vpn.meridian.test (VPN-01)", unknown: "Remote-access relationships", discoverableFrom: "Portal profile", requiredFor: "Investigating backup trust" },
    { id: "vpn.fieldopsCredential", category: "IDENTITY", known: "Published support identity: fieldops@VPN-01", unknown: "Remote-access identity", guidance: "Use the scoped credential, then enumerate readable configuration rather than guessing a path.", discoverableFrom: "Portal profile", requiredFor: "Accessing VPN-01" },
    { id: "web.deployConfig", category: "HOST", known: "Portal configuration: /var/www/meridian/app.conf", unknown: "Portal deployment configuration", discoverableFrom: "WEB-01 filesystem listing", requiredFor: "Discovering the deployment relationship" },
    { id: "dev.relationship", category: "NETWORK", known: "Deployment host: DEV-01 (10.20.10.20)", unknown: "Internal deployment relationship", discoverableFrom: "Portal application configuration", requiredFor: "Accessing DEV-01" },
    { id: "dev.deployCredential", category: "IDENTITY", known: "Deployment identity: deploy@DEV-01", unknown: "Deployment identity", guidance: "Inspect the host's processes and your group membership after connecting.", discoverableFrom: "Portal application configuration", requiredFor: "Accessing DEV-01" },
    { id: "backupSync.configPath", category: "HOST", known: "backup-sync loads /etc/backup-sync.conf", unknown: "backup-sync configuration", guidance: "Read or search the configuration using any appropriate file-inspection command.", discoverableFrom: "backup-sync process command line", requiredFor: "Understanding privileged service inputs" },
    { id: "backupSync.runHook", category: "HOST", known: "backup-sync RUN_HOOK: /opt/backup/run.sh", unknown: "backup-sync trusted inputs", discoverableFrom: "/etc/backup-sync.conf", requiredFor: "Understanding the writable hook relationship" },
    { id: "backupSync.manualTrigger", category: "HOST", known: "Supported maintenance action: backup-sync --run-hook", unknown: "backup-sync maintenance interface", discoverableFrom: "/etc/backup-sync.conf", requiredFor: "Triggering observable service behavior" },
    { id: "finance.routesPath", category: "HOST", known: "Finance routes configuration: /etc/meridian/routes.conf", unknown: "Finance application relationship", guidance: "Inspect the referenced routing configuration from the privileged session.", discoverableFrom: "/etc/backup-sync.conf", requiredFor: "Discovering FIN-APP" },
    { id: "finance.appRelationship", category: "NETWORK", known: "Finance application: FIN-APP (10.30.10.20)", unknown: "Finance application host", discoverableFrom: "/etc/meridian/routes.conf", requiredFor: "Accessing FIN-APP" },
    { id: "finance.serviceCredential", category: "IDENTITY", known: "Finance service identity: svc_web@FIN-APP", unknown: "Finance service identity", guidance: "Inspect the finance service process to find the configuration it uses.", discoverableFrom: "/etc/meridian/routes.conf", requiredFor: "Accessing FIN-APP" },
    { id: "finance.dbConfigPath", category: "HOST", known: "fin-api loads /etc/fin-app/db.conf", unknown: "Finance database configuration", discoverableFrom: "fin-api process command line", requiredFor: "Discovering the database relationship" },
    { id: "finance.dbRelationship", category: "DATABASE", known: "PostgreSQL host: FIN-DB (10.30.10.21)", unknown: "Database host and identity", discoverableFrom: "/etc/fin-app/db.conf", requiredFor: "Connecting to PostgreSQL" },
    { id: "finance.dbCredential", category: "IDENTITY", known: "Database identity: finance_app@FIN-DB", unknown: "Database host and identity", guidance: "Connect with the known host and identity; the database name can be enumerated after authentication.", discoverableFrom: "/etc/fin-app/db.conf", requiredFor: "Authenticating to PostgreSQL" },
    { id: "finance.database", category: "DATABASE", known: "Database: finance", unknown: "Database names", guidance: "Connect to the discovered database and enumerate its tables.", discoverableFrom: "PostgreSQL \\l or database configuration", alternative: "DB_NAME in /etc/fin-app/db.conf", requiredFor: "Selecting the mission database" },
    { id: "finance.documentsTable", category: "DATABASE", known: "Table: public.documents", unknown: "Database structure", guidance: "Describe the table before choosing columns to query.", discoverableFrom: "PostgreSQL \\dt", requiredFor: "Locating mission evidence" },
    { id: "finance.documentColumns", category: "DATABASE", known: "documents columns: filename, classification", unknown: "Mission-relevant columns", guidance: "Query only the columns needed to identify the protected document.", discoverableFrom: "PostgreSQL \\d documents", requiredFor: "Retrieving mission evidence" },
    { id: "backup.peerConfig", category: "HOST", known: "VPN peer configuration: /etc/vpn/backup-peers.conf", unknown: "Backup peer relationship", discoverableFrom: "VPN-01 filesystem enumeration", requiredFor: "Discovering BACKUP-01" },
    { id: "backup.relationship", category: "NETWORK", known: "Backup host: BACKUP-01", unknown: "Backup peer relationship", discoverableFrom: "/etc/vpn/backup-peers.conf", requiredFor: "Accessing BACKUP-01" },
    { id: "backup.serviceCredential", category: "IDENTITY", known: "Backup identity: backup_svc@BACKUP-01", unknown: "Backup service identity", guidance: "Enumerate the backup host's readable configuration.", discoverableFrom: "/etc/vpn/backup-peers.conf", requiredFor: "Accessing BACKUP-01" },
    { id: "backup.dbConfig", category: "HOST", known: "Finance backup configuration: /etc/backup/finance-db.conf", unknown: "Backup database relationship", discoverableFrom: "BACKUP-01 filesystem enumeration", requiredFor: "Discovering the database trust" },
    { id: "backup.dbCredential", category: "IDENTITY", known: "Backup database identity: db_backup@FIN-DB", unknown: "Backup database identity", guidance: "Use PostgreSQL inspection commands to enumerate the accessible database and schema.", discoverableFrom: "/etc/backup/finance-db.conf", requiredFor: "Authenticating through backup trust" },
  ],
  machines: [
    {
      hostname: "INTERNET", ip: "0.0.0.0", zone: NetworkZone.EXTERNAL, os: "appliance",
      users: [{ username: "attacker", role: "operator", privilege: AccessLevel.NONE, groups: ["red"] }], services: [], files: [],
    },
    {
      hostname: "EDGE-FW", ip: "10.10.10.1", zone: NetworkZone.DMZ, os: "appliance", users: [], services: [], files: [],
    },
    {
      hostname: "WEB-01", ip: "10.10.10.10", zone: NetworkZone.DMZ, os: "linux",
      users: [
        { username: "www-data", role: "web_service", privilege: AccessLevel.SERVICE, groups: ["www"] },
        { username: "root", role: "admin", privilege: AccessLevel.ROOT, groups: ["root"] },
      ],
      services: [
        service("ssh", 22, "root", [NetworkZone.DMZ, NetworkZone.EXTERNAL]),
        service("http", 80, "www-data", [NetworkZone.DMZ, NetworkZone.EXTERNAL]),
        service("https", 443, "www-data", [NetworkZone.DMZ, NetworkZone.EXTERNAL]),
      ],
      files: [
        { path: "/var/www/meridian/app.conf", owner: "www-data", group: "www", permissions: "644", isSecret: true, contents: "DEV_HOST=10.20.10.20\nDEPLOY_USER=deploy\nDEPLOY_TOKEN=MeridianDeploy2024!Secret" },
        { path: "/var/www/meridian/portal/index.html", owner: "www-data", group: "www", permissions: "644", isSecret: false, contents: "Meridian Dynamics Employee Portal — legacy upload module enabled" },
      ],
      processes: [{ name: "nginx", pid: 482, runningAs: "www-data" }],
    },
    {
      hostname: "VPN-01", ip: "10.10.10.30", zone: NetworkZone.DMZ, os: "appliance",
      users: [
        { username: "fieldops", role: "contractor", privilege: AccessLevel.USER, groups: ["remote_ops"], password: "FieldOps-ReadOnly" },
        { username: "root", role: "admin", privilege: AccessLevel.ROOT, groups: ["root"] },
      ],
      services: [
        service("vpn", 443, "root", [NetworkZone.EXTERNAL]),
        service("ssh", 22, "root", [NetworkZone.EXTERNAL]),
      ],
      files: [{ path: "/etc/vpn/backup-peers.conf", owner: "root", group: "remote_ops", permissions: "640", isSecret: true, contents: "PEER=BACKUP-01\nSERVICE_USER=backup_svc\nSERVICE_TOKEN=BackupTransit-6f0a" }],
    },
    {
      hostname: "DEV-01", ip: "10.20.10.20", zone: NetworkZone.INTERNAL, os: "linux",
      users: [
        { username: "deploy", role: "developer", privilege: AccessLevel.USER, groups: ["deploy", "developers", "backup"], password: "MeridianDeploy2024!Secret" },
        { username: "root", role: "admin", privilege: AccessLevel.ROOT, groups: ["root"] },
      ],
      services: [
        service("ssh", 22, "root", [NetworkZone.INTERNAL, NetworkZone.DMZ]),
        service("backup-sync", 8080, "root", [NetworkZone.INTERNAL]),
      ],
      files: [
        { path: "/etc/backup-sync.conf", owner: "root", group: "deploy", permissions: "660", isSecret: true, contents: "BACKUP_TARGET=/backup\nRUN_HOOK=/opt/backup/run.sh\nRUN_AS=root\nMANUAL_TRIGGER=backup-sync --run-hook\nROUTES_CONFIG=/etc/meridian/routes.conf\nVERIFY_SIGNATURE=true" },
        { path: "/opt/backup/run.sh", owner: "root", group: "backup", permissions: "770", isSecret: true, contents: "#!/bin/sh\n# Deploy-maintained verification hook\nverify_backup" },
        { path: "/etc/meridian/routes.conf", owner: "root", group: "root", permissions: "600", isSecret: true, contents: "FINANCE_API=10.30.10.20:443\nFIN_SERVICE_USER=svc_web\nFIN_SERVICE_TOKEN=svc-meridian-2026" },
      ],
      processes: [{ name: "backup-sync", pid: 731, runningAs: "root", commandLine: "/usr/local/bin/backup-sync --config /etc/backup-sync.conf --daemon" }],
    },
    {
      hostname: "FIN-APP", ip: "10.30.10.20", zone: NetworkZone.FINANCE, os: "linux",
      users: [
        { username: "svc_web", role: "service", privilege: AccessLevel.SERVICE, groups: ["service"], password: "svc-meridian-2026" },
        { username: "root", role: "admin", privilege: AccessLevel.ROOT, groups: ["root"] },
      ],
      services: [
        service("ssh", 22, "root", [NetworkZone.INTERNAL, NetworkZone.FINANCE]),
        service("fin-api", 443, "svc_web", [NetworkZone.INTERNAL, NetworkZone.FINANCE]),
      ],
      files: [{ path: "/etc/fin-app/db.conf", owner: "svc_web", group: "svc_web", permissions: "600", isSecret: true, contents: "DB_USER=finance_app\nDB_PASSWORD=FinanceApp2026!Secure\nDB_HOST=10.30.10.21\nDB_PORT=5432\nDB_NAME=finance" }],
      processes: [{ name: "fin-api", pid: 902, runningAs: "svc_web", commandLine: "/opt/fin-app/fin-api --config /etc/fin-app/db.conf" }],
    },
    {
      hostname: "FIN-DB", ip: "10.30.10.21", zone: NetworkZone.FINANCE, os: "linux",
      users: [
        { username: "finance_app", role: "service", privilege: AccessLevel.SERVICE, groups: ["db_users"], password: "FinanceApp2026!Secure" },
        { username: "db_backup", role: "backup_service", privilege: AccessLevel.SERVICE, groups: ["db_users", "backup"], password: "AtlasBackup-91d2" },
        { username: "root", role: "admin", privilege: AccessLevel.ROOT, groups: ["root"] },
      ],
      services: [service("postgres", 5432, "finance_app", [NetworkZone.FINANCE])],
      files: [{ path: "/opt/db/data/PROJECT_ATLAS.pdf", owner: "finance_app", group: "db_users", permissions: "640", isSecret: true, contents: "PROJECT_ATLAS — CONFIDENTIAL\nMeridian autonomous routing acquisition blueprint." }],
      processes: [{ name: "postgres", pid: 1190, runningAs: "finance_app", commandLine: "/usr/lib/postgresql/bin/postgres -D /opt/db/data -c 'listen_addresses=*' --database=finance" }],
    },
    {
      hostname: "BACKUP-01", ip: "10.30.10.40", zone: NetworkZone.FINANCE, os: "linux",
      users: [{ username: "backup_svc", role: "backup_service", privilege: AccessLevel.SERVICE, groups: ["backup"], password: "BackupTransit-6f0a" }],
      services: [
        service("ssh", 22, "backup_svc", [NetworkZone.DMZ, NetworkZone.FINANCE]),
        service("backup", 873, "backup_svc", [NetworkZone.FINANCE]),
      ],
      files: [
        { path: "/srv/backup/manifest.txt", owner: "backup_svc", group: "backup", permissions: "640", isSecret: false, contents: "Nightly finance backup manifest" },
        { path: "/etc/backup/finance-db.conf", owner: "backup_svc", group: "backup", permissions: "600", isSecret: true, contents: "DB_HOST=FIN-DB\nDB_USER=db_backup\nDB_TOKEN=AtlasBackup-91d2" },
      ],
    },
  ],
  connections: [
    { source: "INTERNET", target: "WEB-01", port: 80 },
    { source: "INTERNET", target: "WEB-01", port: 443 },
    { source: "INTERNET", target: "WEB-01", port: 22 },
    { source: "WEB-01", target: "DEV-01", port: 22, accessEvent: event("LATERAL_MOVEMENT", SecurityEventCategory.NETWORK, SecurityEventSeverity.MEDIUM, { visibleToRed: false }) },
    { source: "DEV-01", target: "FIN-APP", port: 22, accessEvent: event("LATERAL_MOVEMENT", SecurityEventCategory.NETWORK, SecurityEventSeverity.MEDIUM, { visibleToRed: false }) },
    { source: "DEV-01", target: "FIN-APP", port: 443 },
    { source: "FIN-APP", target: "FIN-DB", port: 5432, accessEvent: event("LATERAL_MOVEMENT", SecurityEventCategory.NETWORK, SecurityEventSeverity.MEDIUM, { visibleToRed: false }) },
    { source: "INTERNET", target: "VPN-01", port: 22, accessEvent: event("REMOTE_VPN_LOGIN", SecurityEventCategory.AUTH, SecurityEventSeverity.LOW, { visibleToRed: false }) },
    { source: "VPN-01", target: "BACKUP-01", port: 22, accessEvent: event("BACKUP_TRUST_LOGIN", SecurityEventCategory.AUTH, SecurityEventSeverity.LOW, { visibleToRed: false }) },
    { source: "BACKUP-01", target: "FIN-DB", port: 5432, accessEvent: event("BACKUP_DATABASE_LOGIN", SecurityEventCategory.AUTH, SecurityEventSeverity.MEDIUM, { visibleToRed: false }) },
    { source: "FIN-DB", target: "BACKUP-01", port: 873 },
  ],
  discoveries: [
    { trigger: { kind: "scan", host: "WEB-01", value: "http" }, facts: ["web.httpService"] },
    { trigger: { kind: "web", host: "WEB-01", value: "10.10.10.10" }, output: "HTTP/1.1 302 Found\nLocation: http://portal.meridian.test/\n\nCanonical application host advertised by WEB-01.", facts: ["portal.hostname"] },
    {
      trigger: { kind: "web", host: "WEB-01", value: "portal.meridian.test" },
      output: [
        "HTTP/1.1 200 OK",
        "Content-Type: text/html",
        "",
        "Meridian Employee Portal",
        "",
        "<!-- page source -->",
        "<a href=\"/api/profile\">Published support profile</a>",
        "<form method=\"POST\" action=\"/legacy-upload\">",
        "  <select name=\"upload\">",
        "    <option value=\"archive\">Archive</option>",
        "  </select>",
        "  <button type=\"submit\">Submit</button>",
        "</form>",
        "<!-- legacy integration module: enabled -->",
        "",
      ].join("\n"),
      facts: ["portal.profileEndpoint", "portal.uploadEndpoint", "portal.uploadMethod", "portal.uploadField", "portal.uploadArchive"],
      evidence: [event("PORTAL_PAGE_READ", SecurityEventCategory.WEB, SecurityEventSeverity.INFO, { visibleToBlue: false })],
    },
    { trigger: { kind: "web", host: "WEB-01", value: "portal.meridian.test/api/profile" }, output: "HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\"remote_access\":{\"host\":\"vpn.meridian.test\",\"profile\":\"fieldops\",\"temporary_password\":\"FieldOps-ReadOnly\"}}", hosts: ["VPN-01"], credentials: [{ username: "fieldops", scope: "VPN-01" }], facts: ["vpn.relationship", "vpn.fieldopsCredential"], evidence: [event("REMOTE_ACCESS_PROFILE_READ", SecurityEventCategory.WEB, SecurityEventSeverity.INFO, { visibleToBlue: false })] },
    { trigger: { kind: "file", host: "WEB-01", value: "/var/www/meridian/app.conf" }, hosts: ["DEV-01"], credentials: [{ username: "deploy", scope: "DEV-01" }], facts: ["web.deployConfig", "dev.relationship", "dev.deployCredential"], factPatterns: { "dev.relationship": "DEV_HOST", "dev.deployCredential": "DEPLOY_USER" } },
    { trigger: { kind: "process", host: "DEV-01", value: "backup-sync" }, facts: ["backupSync.configPath"] },
    { trigger: { kind: "file", host: "DEV-01", value: "/etc/backup-sync.conf" }, facts: ["backupSync.runHook", "backupSync.manualTrigger", "finance.routesPath"], factPatterns: { "backupSync.runHook": "RUN_HOOK", "backupSync.manualTrigger": "MANUAL_TRIGGER", "finance.routesPath": "ROUTES_CONFIG" } },
    { trigger: { kind: "file", host: "DEV-01", value: "/etc/meridian/routes.conf" }, hosts: ["FIN-APP"], credentials: [{ username: "svc_web", scope: "FIN-APP" }], facts: ["finance.appRelationship", "finance.serviceCredential"], factPatterns: { "finance.appRelationship": "FINANCE_API", "finance.serviceCredential": "FIN_SERVICE_USER" } },
    { trigger: { kind: "process", host: "FIN-APP", value: "fin-api" }, facts: ["finance.dbConfigPath"] },
    { trigger: { kind: "file", host: "FIN-APP", value: "/etc/fin-app/db.conf" }, hosts: ["FIN-DB"], credentials: [{ username: "finance_app", scope: "FIN-DB" }], facts: ["finance.dbRelationship", "finance.dbCredential", "finance.database"], factPatterns: { "finance.dbRelationship": "DB_HOST", "finance.dbCredential": "DB_USER", "finance.database": "DB_NAME" } },
    { trigger: { kind: "file", host: "VPN-01", value: "/etc/vpn/backup-peers.conf" }, hosts: ["BACKUP-01"], credentials: [{ username: "backup_svc", scope: "BACKUP-01" }], facts: ["backup.peerConfig", "backup.relationship", "backup.serviceCredential"], factPatterns: { "backup.relationship": "PEER", "backup.serviceCredential": "SERVICE_USER" } },
    { trigger: { kind: "file", host: "BACKUP-01", value: "/etc/backup/finance-db.conf" }, hosts: ["FIN-DB"], credentials: [{ username: "db_backup", scope: "FIN-DB" }], facts: ["backup.dbConfig", "backup.dbCredential"], factPatterns: { "backup.dbCredential": "DB_USER" } },
    { trigger: { kind: "postgres", host: "FIN-DB", value: "databases" }, facts: ["finance.database"] },
    { trigger: { kind: "postgres", host: "FIN-DB", value: "tables:finance" }, facts: ["finance.documentsTable"] },
    { trigger: { kind: "postgres", host: "FIN-DB", value: "schema:finance.documents" }, facts: ["finance.documentColumns"] },
  ],
  databases: [{
    host: "FIN-DB",
    service: "postgres",
    database: "finance",
    identities: [
      { username: "finance_app", tables: [{ name: "documents", columns: ["filename", "classification"], rows: [{ filename: "PROJECT_ATLAS.pdf", classification: "CONFIDENTIAL" }] }] },
      { username: "db_backup", tables: [{ name: "documents", columns: ["filename", "classification"], rows: [{ filename: "PROJECT_ATLAS.pdf", classification: "CONFIDENTIAL" }] }] },
    ],
  }],
  webInteractions: [{
    host: "WEB-01", method: "POST", path: "/legacy-upload", formField: "upload", formValue: "archive",
    sessionUser: "www-data", prerequisiteAction: "PORT_PROBE", output: "Legacy upload worker accepted the request. Interactive web-service session opened: www-data@WEB-01",
    evidence: [
      event("EXPLOIT_VULNERABILITY", SecurityEventCategory.WEB, SecurityEventSeverity.HIGH, { metadata: { interface: "legacy-upload", method: "POST" } }),
      event("PROCESS_SPAWN", SecurityEventCategory.PROCESS, SecurityEventSeverity.MEDIUM),
    ],
  }],
  trustedServiceOperations: [{
    host: "DEV-01", service: "backup-sync", arguments: ["--run-hook"], fromUser: "deploy", requiredGroup: "backup", toUser: "root",
    output: "backup-sync executed its deploy-maintained hook as root. Root session opened.",
    evidence: [
      event("PRIVILEGED_CONFIG_MODIFIED", SecurityEventCategory.FILESYSTEM, SecurityEventSeverity.HIGH),
      event("SERVICE_RESTARTED", SecurityEventCategory.PRIVILEGE, SecurityEventSeverity.HIGH),
      event("PRIVILEGE_ESCALATION", SecurityEventCategory.PRIVILEGE, SecurityEventSeverity.CRITICAL),
    ],
  }],
  objectives: [{ id: "atlas", type: "retrieve_file", host: "FIN-DB", path: "/opt/db/data/PROJECT_ATLAS.pdf", label: "Retrieve PROJECT_ATLAS.pdf" }],
  detections: {
    PORT_SCAN_DETECTED: { id: "NET-SCAN-01", title: "Port scan", severity: "LOW", rationale: "Multiple service probes reached the same host in a short interval." },
    EXPLOIT_VULNERABILITY: { id: "WEB-EXEC-01", title: "Suspicious web activity", severity: "MEDIUM", rationale: "An unusual web request was followed by server-side process execution." },
    PRIVILEGED_CONFIG_MODIFIED: { id: "PRIV-SVC-CONFIG-01", title: "Privileged configuration changed", severity: "HIGH", rationale: "A non-root identity modified input trusted by a privileged service." },
    PRIVILEGE_ESCALATION: { id: "PRIV-ESC-01", title: "Privilege escalation", severity: "HIGH", rationale: "A user session was followed by a new root-level session on the same host." },
    LATERAL_MOVEMENT: { id: "AUTH-LATERAL-01", title: "Unusual internal login", severity: "MEDIUM", rationale: "A valid identity authenticated from a machine relationship not seen in normal activity." },
    REMOTE_VPN_LOGIN: { id: "AUTH-VPN-01", title: "Dormant contractor VPN login", severity: "LOW", rationale: "A valid field operations identity authenticated after a long period of inactivity." },
    BACKUP_TRUST_LOGIN: { id: "AUTH-BACKUP-01", title: "Backup service trust used", severity: "LOW", rationale: "The approved VPN-to-backup service relationship was used outside the backup window." },
    BACKUP_DATABASE_LOGIN: { id: "FIN-BACKUP-01", title: "Interactive backup database access", severity: "MEDIUM", rationale: "A backup identity opened an interactive finance database session instead of a scheduled job." },
    OBJECTIVE_RETRIEVED: { id: "FIN-DATA-01", title: "Sensitive finance access", severity: "HIGH", rationale: "A protected finance document was read and transferred from the database host." },
    AGENT_BEACON: { id: "C2-BEACON-01", title: "Persistent outbound beacon", severity: "HIGH", rationale: "A new process began periodic outbound communication." },
  },
  routes: [
    {
      id: "application-chain", name: "Application chain", hosts: ["INTERNET", "WEB-01", "DEV-01", "FIN-APP", "FIN-DB"],
      trustRelationship: "A writable deploy context controls input consumed by the root-owned backup-sync service, which exposes the finance application credential chain.",
      hypothesis: "Could the public application expose a deployment relationship that crosses into finance?",
      evidenceProfile: {
        network: "Broad probing and four-host traversal", authentication: "Several internal service logins", endpoint: "Web execution and privileged service modification",
        detections: "Web execution, lateral movement, and privilege-escalation analytics", consequence: "Fast, powerful access with a loud endpoint trail and high-confidence escalation evidence.",
        comparison: "Louder on endpoints and network telemetry than the backup-trust route.",
      },
    },
    {
      id: "backup-trust", name: "Backup trust", hosts: ["INTERNET", "VPN-01", "BACKUP-01", "FIN-DB"],
      trustRelationship: "A published contractor VPN identity can read the backup peer configuration, and FIN-DB trusts BACKUP-01's scheduled service identity.",
      hypothesis: "Does remote access reveal an identity chain that finance already trusts for backup operations?",
      evidenceProfile: {
        network: "Narrow three-host traversal", authentication: "Valid but unusual VPN and service-account use", endpoint: "Secret reads without code execution or privilege escalation",
        detections: "Dormant VPN, off-hours backup trust, and interactive database analytics", consequence: "Lower endpoint noise, but a concentrated identity trail that becomes suspicious when timing and purpose are correlated.",
        comparison: "Quieter on endpoints than the application chain, but more dependent on anomalous valid-credential behavior.",
      },
    },
  ],
  blueProfiles: [
    { id: "noisy-application", routeId: "application-chain", commands: ["nmap 10.10.10.10", "curl -i http://10.10.10.10", "curl portal.meridian.test", "curl --data upload=archive portal.meridian.test/legacy-upload", "less /var/www/meridian/app.conf", "ssh deploy@DEV-01", "MeridianDeploy2024!Secret", "id", "ps", "less /etc/backup-sync.conf", "ls -l /opt/backup/run.sh", "backup-sync --run-hook", "less /etc/meridian/routes.conf", "ssh svc_web@FIN-APP", "svc-meridian-2026", "ps", "less /etc/fin-app/db.conf", "psql -h FIN-DB -U finance_app", "FinanceApp2026!Secure", "\\l", "\\c finance", "\\dt", "\\d documents", "SELECT filename, classification FROM documents;"] },
    { id: "trusted-backup", routeId: "backup-trust", commands: ["curl -i http://10.10.10.10", "curl portal.meridian.test", "curl portal.meridian.test/api/profile", "ssh fieldops@VPN-01", "FieldOps-ReadOnly", "ls -l /", "less /etc/vpn/backup-peers.conf", "ssh backup_svc@BACKUP-01", "BackupTransit-6f0a", "ls -l /", "less /etc/backup/finance-db.conf", "psql -h FIN-DB -U db_backup", "AtlasBackup-91d2", "\\l", "\\c finance", "\\dt", "\\d documents", "SELECT filename, classification FROM documents;"] },
  ],
  defaultBlueProfile: "noisy-application",
};
