import type { ScenarioDefinition } from "./types";
import { commonDetections, discover, dns, external, file, guidedOnboarding, host, identity, link, route, withObjectiveHints } from "./content";

export const noOneKnows: ScenarioDefinition = {
  id: "no-one-knows", name: "Operation No One Knows", organization: "Halcyon Utilities",
  presentation: { caseId: "IR-25", order: 14, prerequisite: "ghost-account", focus: ["Hypothesis testing", "Containment", "Availability"] },
  briefing: { red: "A vendor diagnostics service and an emergency status portal both have paths to the protected restoration plan. Retrieve RESTORATION_PLAN.pdf without triggering a broad shutdown.", blue: "Conflicting evidence suggests either an approved emergency workflow or an active intrusion. Form a defensible hypothesis, stop the actual route, and keep restoration planning available.", constraints: ["Ambiguity is not a reason to shut down every service", "Containment must preserve restoration planning above 60% availability"] },
  availableModes: ["RED", "BLUE"], assistance: { guided: guidedOnboarding, operator: "Use evidence to state which relationship is compromised, contain it, and prove the independent business path remains available." },
  conditions: { timeLimitMinutes: 90, minimumAvailability: 60 }, dnsRecords: dns({ "status.halcyon.test": "STATUS-WEB" }), startingKnowledge: { knownHosts: ["INTERNET", "STATUS-WEB"], knownAssets: ["status.halcyon.test"] },
  machines: [external, host("STATUS-WEB", "10.91.1.10", "DMZ", [identity("root", "ROOT")], [file("/etc/status/restoration.conf", "root", "PLAN_HOST=PLAN-01\nUSER=plan_svc\nTOKEN=halcyon-plan")], true), host("VENDOR-DIAG", "10.91.1.30", "DMZ", [identity("mia")], [file("/home/mia/diagnostics.txt", "mia", "Vendor diagnostics can read PLAN-01 as plan_svc during approved restoration tests. The plan is not exported during diagnostics.")]), host("PLAN-01", "10.91.2.10", "INTERNAL", [identity("plan_svc", "SERVICE")], [file("/srv/restoration/RESTORATION_PLAN.pdf", "plan_svc", "SIMULATED HALCYON RESTORATION PLAN")]), host("CONTROL-01", "10.91.2.30", "INTERNAL", [identity("control_svc", "SERVICE")])],
  connections: [link("INTERNET", "STATUS-WEB", 443), link("INTERNET", "VENDOR-DIAG", 22, "VENDOR_DIAGNOSTIC_LOGIN"), link("STATUS-WEB", "PLAN-01", 22, "STATUS_PLAN_LOGIN"), link("VENDOR-DIAG", "PLAN-01", 22, "VENDOR_PLAN_LOGIN"), link("CONTROL-01", "PLAN-01", 22)],
  discoveries: [{ trigger: { kind: "web", host: "STATUS-WEB", value: "status.halcyon.test" }, output: "Halcyon emergency status\nVendor diagnostics: mia@VENDOR-DIAG / HalcyonDiag-62\nStatus reconciliation worker enabled.", hosts: ["VENDOR-DIAG"], credentials: [{ username: "mia", scope: "VENDOR-DIAG" }] }, discover("STATUS-WEB", "/etc/status/restoration.conf", "PLAN-01", "plan_svc"), discover("VENDOR-DIAG", "/home/mia/diagnostics.txt", "PLAN-01", "plan_svc")],
  webInteractions: [{ host: "STATUS-WEB", method: "POST", path: "/status/reconcile", dataIncludes: "update=emergency", sessionUser: "root", prerequisiteAction: "PORT_PROBE", output: "The emergency reconciliation worker accepted the public update as root. Session opened.", evidence: [{ action: "WEB_WORKER_EXECUTED", category: "WEB", severity: "HIGH" }, { action: "PROCESS_SPAWN", category: "PROCESS", severity: "HIGH" }] }], objectives: withObjectiveHints("no-one-knows", [{ id: "restoration-plan", type: "retrieve_file", host: "PLAN-01", path: "/srv/restoration/RESTORATION_PLAN.pdf", label: "Retrieve RESTORATION_PLAN.pdf" }]),
  detections: { ...commonDetections, VENDOR_DIAGNOSTIC_LOGIN: { id: "AUTH-DIAG-01", title: "Vendor diagnostic login", severity: "LOW", rationale: "Diagnostics are approved only during restoration testing and do not include plan export." }, STATUS_PLAN_LOGIN: { id: "AUTH-STATUS-01", title: "Status worker reached restoration plan", severity: "MEDIUM", rationale: "A public status service opened an interactive restoration-plan session." }, VENDOR_PLAN_LOGIN: { id: "AUTH-DIAG-02", title: "Vendor diagnostic path reached plan", severity: "HIGH", rationale: "A vendor path reused the plan identity beyond its diagnostic purpose." } },
  routes: [route("status-worker", "Status worker", ["INTERNET", "STATUS-WEB", "PLAN-01"], "A root emergency-status worker holds the restoration-plan credential and is loudly observable.", "Is a public status workflow being used to access restoration planning?", true), route("vendor-diagnostics", "Vendor diagnostics", ["INTERNET", "VENDOR-DIAG", "PLAN-01"], "A vendor diagnostic relationship is legitimate only during approved testing and never for plan export.", "Has diagnostic access crossed into restoration-plan disclosure?", false)],
  blueProfiles: [{ id: "status-worker", routeId: "status-worker", commands: ["nmap STATUS-WEB", "curl -X POST status.halcyon.test/status/reconcile --data update=emergency", "cat /etc/status/restoration.conf", "ssh plan_svc@PLAN-01", "retrieve RESTORATION_PLAN.pdf"] }, { id: "vendor-diagnostics", routeId: "vendor-diagnostics", commands: ["curl status.halcyon.test", "ssh mia@VENDOR-DIAG", "cat /home/mia/diagnostics.txt", "ssh plan_svc@PLAN-01", "retrieve RESTORATION_PLAN.pdf"] }], defaultBlueProfile: "vendor-diagnostics",
  securityControls: [{ host: "STATUS-WEB", telemetry: ["WEB", "NETWORK", "PROCESS", "AUTH"] }, { host: "VENDOR-DIAG", telemetry: ["AUTH", "NETWORK"] }, { host: "PLAN-01", telemetry: ["AUTH", "FILESYSTEM"] }], businessServices: [{ name: "Emergency status", hosts: ["STATUS-WEB"], impact: "Public outage status becomes unavailable." }, { name: "Restoration planning", hosts: ["PLAN-01"], impact: "Operators cannot coordinate restoration." }, { name: "Control coordination", hosts: ["CONTROL-01"], impact: "Control-room updates are delayed." }], persistencePolicy: { process: "status-health-agent", requiredPrivilege: "ROOT", beaconSeconds: 30 }, knowledgeRewards: [{ concept: "Evidence correlation", actions: ["INCIDENT_FINDING", "VENDOR_PLAN_LOGIN"] }, { concept: "Incident response", actions: ["BLOCK_CONNECTION", "ATTACK_CONTAINED"] }, { concept: "Business impact", actions: ["HOST_ISOLATED", "HOST_RESTORED"] }], backgroundActivity: [{ host: "PLAN-01", source: "CONTROL-01", user: "plan_svc", action: "AUTH_SUCCESS", context: "Approved control-room synchronization; restoration plans are not exported interactively." }],
};
