import { AccessLevel, NetworkZone } from "@/app/generated/prisma/enums";
import type { ScenarioDefinition } from "./types";
import { dns, service } from "./content";

const learning = (
  concepts: string[],
  evidence: string,
  domain: "COMPUTING_OS" | "NETWORKING" | "SECURITY_REASONING" = "NETWORKING",
): NonNullable<ScenarioDefinition["objectives"][number]["learning"]> => ({
  domain,
  concepts,
  stage: "PRACTICED",
  evidence,
});

export const serviceUnavailable: ScenarioDefinition = {
  id: "service-unavailable",
  name: "Service Unavailable",
  organization: "Nodeline Security",
  briefing: {
    red: "The internal reporting site is unreachable for the finance team. Determine whether REPORTS-01 itself is down or whether only the reporting service has failed, using only evidence you find.",
    blue: "This orientation assignment has no defensive role.",
    constraints: ["Use the bounded ROOT/OS terminal", "Treat command output and local documentation as evidence", "Confirm a service's actual state before assuming a host is down"],
  },
  objectiveSummary: "Diagnose a stopped web service on an otherwise reachable host",
  presentation: { caseId: "NET-02", focus: ["Ports", "Services", "SSH"], order: 4, prerequisite: "website-down" },
  availableModes: ["RED"],
  assistance: {
    guided: [
      "Read the ticket, then ping REPORTS-01 before assuming the whole host is offline.",
      "A host answering ping can still have a stopped service. Scan it to see which ports are actually open.",
      "Read the standard access note for how helpdesk reaches internal hosts, then SSH in and check what the reporting process is actually doing.",
    ],
    operator: "Use the trouble ticket and the standard access note as your only procedure. Confirm the service's state directly rather than assuming from the outage report.",
    operatorAvailableAtStart: true,
  },
  conditions: { timeLimitMinutes: 20, minimumAvailability: 100 },
  securityControls: [{ host: "HELPDESK-01", telemetry: ["SYSTEM", "FILESYSTEM"] }, { host: "REPORTS-01", telemetry: ["NETWORK", "SYSTEM", "FILESYSTEM", "PROCESS"] }],
  businessServices: [{ name: "Internal reporting", hosts: ["REPORTS-01"], impact: "Finance cannot generate daily reports." }],
  persistencePolicy: { process: "helpdesk-agent", requiredPrivilege: AccessLevel.ROOT, beaconSeconds: 60 },
  knowledgeRewards: [],
  backgroundActivity: [],
  dnsRecords: dns({ "helpdesk-01.nodeline.test": "HELPDESK-01", "reports.nodeline.test": "REPORTS-01" }),
  startingKnowledge: { knownHosts: ["HELPDESK-01"], knownAssets: [] },
  startingSession: { host: "HELPDESK-01", user: "trainee", path: "/home/trainee" },
  facts: [
    {
      id: "reports.ticket",
      category: "NETWORK",
      known: "Finance reports reports.nodeline.test has been unreachable since this morning.",
      unknown: "Whether REPORTS-01 itself is down or only a service on it has failed",
      guidance: "Read the trouble ticket before touching the network.",
      discoverableFrom: "/home/trainee/TICKET-5188.txt",
      requiredFor: "Scoping the investigation to the reported service",
    },
    {
      id: "reports.hostUp",
      category: "NETWORK",
      known: "REPORTS-01 answers ping and its SSH port is open.",
      unknown: "Whether the host being up means the reporting service is fine",
      guidance: "Ping the host before assuming the outage means it is offline.",
      discoverableFrom: "ping output for REPORTS-01",
      requiredFor: "Ruling out a total host outage",
    },
    {
      id: "reports.portClosed",
      category: "NETWORK",
      known: "REPORTS-01's HTTPS port is closed even though the host is reachable and SSH is open.",
      unknown: "Whether the reporting application is running at all",
      guidance: "Scan the host to see which ports are actually open, not just whether it answers ping.",
      discoverableFrom: "nmap output for REPORTS-01",
      requiredFor: "Narrowing the failure to a single stopped service",
    },
    {
      id: "reports.standardAccess",
      category: "IDENTITY",
      known: "Helpdesk trainees use a standard SSH credential for internal Nodeline hosts.",
      unknown: "The username and password needed to log in to REPORTS-01",
      guidance: "Read the standard access note before trying to guess a login.",
      discoverableFrom: "/home/trainee/STANDARD_ACCESS.txt",
      requiredFor: "Logging in to REPORTS-01 to confirm the process state directly",
    },
    {
      id: "reports.processCrashed",
      category: "HOST",
      known: "reports-app is not running; its log shows it exited after a configuration read failure at startup.",
      unknown: "Why HTTPS never came back up even though the host itself is healthy",
      guidance: "Check the process table and the reporting app log once logged in.",
      discoverableFrom: "/var/log/reports-app.log",
      requiredFor: "Explaining the outage as a stopped service rather than a host failure",
    },
  ],
  machines: [
    {
      hostname: "HELPDESK-01",
      ip: "10.0.0.20",
      zone: NetworkZone.INTERNAL,
      os: "linux",
      users: [
        { username: "trainee", role: "operator_trainee", privilege: AccessLevel.USER, groups: ["trainees", "operations"] },
        { username: "root", role: "administrator", privilege: AccessLevel.ROOT, groups: ["root"] },
      ],
      services: [],
      files: [
        {
          path: "/home/trainee/TICKET-5188.txt",
          owner: "trainee",
          group: "trainees",
          permissions: "640",
          isSecret: false,
          contents: [
            "TICKET 5188 // Reporting site unreachable",
            "",
            "Reported: reports.nodeline.test has been unreachable since this morning. Finance cannot generate daily reports.",
            "Determine whether REPORTS-01 is down or only a service on it has failed, and record the cause with evidence.",
          ].join("\n"),
        },
        {
          path: "/home/trainee/STANDARD_ACCESS.txt",
          owner: "trainee",
          group: "trainees",
          permissions: "640",
          isSecret: false,
          contents: [
            "HELPDESK // Standard internal host access",
            "",
            "Helpdesk trainees may log in to internal Nodeline hosts with the standard support credential:",
            "  user: trainee",
            "  password: Helpdesk#2024",
            "",
            "Use this credential only to diagnose the reported issue.",
          ].join("\n"),
        },
      ],
      processes: [{ name: "sshd", pid: 130, runningAs: "root", commandLine: "/usr/sbin/sshd -D" }],
    },
    {
      hostname: "REPORTS-01",
      ip: "10.0.0.60",
      zone: NetworkZone.INTERNAL,
      os: "linux",
      users: [
        { username: "trainee", role: "operator_trainee", privilege: AccessLevel.USER, groups: ["trainees"], password: "Helpdesk#2024" },
        { username: "reports-svc", role: "report_service", privilege: AccessLevel.SERVICE, groups: ["reports-svc"] },
        { username: "root", role: "administrator", privilege: AccessLevel.ROOT, groups: ["root"] },
      ],
      services: [service("ssh", 22, "root", [NetworkZone.INTERNAL]), service("https", 443, "reports-svc", [NetworkZone.INTERNAL], "STOPPED")],
      files: [
        {
          path: "/var/log/reports-app.log",
          owner: "root",
          group: "sysadmin",
          permissions: "644",
          isSecret: false,
          contents: [
            "2026-09-19 06:02:11 reports-app[880]: INFO starting reports-app",
            "2026-09-19 06:02:11 reports-app[880]: ERROR failed to read /etc/reports-app/config.yml: not found",
            "2026-09-19 06:02:11 reports-app[880]: FATAL exiting after configuration read failure",
          ].join("\n"),
        },
      ],
      processes: [{ name: "sshd", pid: 121, runningAs: "root", commandLine: "/usr/sbin/sshd -D" }],
    },
  ],
  connections: [
    { source: "HELPDESK-01", target: "REPORTS-01", port: 22 },
  ],
  discoveries: [
    { trigger: { kind: "file", host: "HELPDESK-01", value: "/home/trainee/TICKET-5188.txt" }, facts: ["reports.ticket"] },
    { trigger: { kind: "file", host: "HELPDESK-01", value: "/home/trainee/STANDARD_ACCESS.txt" }, hosts: ["REPORTS-01"], facts: ["reports.standardAccess"], credentials: [{ username: "trainee", scope: "REPORTS-01" }] },
    { trigger: { kind: "scan", host: "REPORTS-01", value: "ssh" }, facts: ["reports.hostUp"] },
    { trigger: { kind: "scan", host: "REPORTS-01", value: "https" }, facts: ["reports.portClosed"] },
    { trigger: { kind: "file", host: "REPORTS-01", value: "/var/log/reports-app.log" }, facts: ["reports.processCrashed"] },
  ],
  objectives: [
    { id: "locate-session", type: "event", label: "Establish the current directory", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "CURRENT_DIRECTORY" } }, learning: learning(["Files and directories", "Command-line navigation"], "Observed the active shell working directory with pwd.", "COMPUTING_OS") },
    { id: "identify-user", type: "event", label: "Identify the current user", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "CURRENT_USER" } }, learning: learning(["Users"], "Observed the session username with whoami.", "COMPUTING_OS") },
    { id: "inspect-groups", type: "event", label: "Inspect identity and group membership", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "IDENTITY_GROUPS" } }, learning: learning(["Users and groups"], "Observed identity, privilege, and group membership with id.", "COMPUTING_OS") },
    { id: "inspect-environment", type: "event", label: "Inspect the session environment", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "ENVIRONMENT" } }, learning: learning(["Environment variables", "Current host"], "Observed host and session context through environment variables.", "COMPUTING_OS") },
    { id: "review-ticket", type: "fact", factId: "reports.ticket", label: "Read the trouble ticket", learning: learning(["Documentation", "Evidence versus assumptions"], "Read the trouble ticket and scoped the investigation to the reported service.", "SECURITY_REASONING") },
    { id: "confirm-host-up", type: "fact", factId: "reports.hostUp", label: "Confirm the host itself is reachable", learning: learning(["Hosts", "Reachability"], "Pinged and scanned REPORTS-01 and confirmed it is up and its SSH port is open.") },
    { id: "confirm-port-closed", type: "fact", factId: "reports.portClosed", label: "Identify the closed service port", learning: learning(["Ports", "Services"], "Scanned REPORTS-01 and found its HTTPS port closed while SSH remained open, narrowing the failure to one service.", "SECURITY_REASONING") },
    { id: "discover-access", type: "fact", factId: "reports.standardAccess", label: "Find the standard internal access credential", learning: learning(["Users", "SSH", "Documentation"], "Identified the documented standard credential for internal hosts rather than guessing one.", "SECURITY_REASONING") },
    { id: "authenticate-reports", type: "event", label: "Log in to REPORTS-01", event: { action: "SESSION_CREATED", targetHost: "REPORTS-01", userId: "trainee" }, learning: learning(["SSH", "Users"], "Authenticated to REPORTS-01 using the documented standard credential.") },
    { id: "correlate-cause", type: "fact", factId: "reports.processCrashed", label: "Explain the outage as a crashed service", learning: learning(["Processes", "Services", "Evidence versus assumptions"], "Read the reporting app log and confirmed the service had exited on a configuration error, rather than the host being down.", "SECURITY_REASONING") },
  ],
  objectiveCompletion: "ALL",
  beginnerExitQuestions: [
    { id: "current-host", prompt: "What host are you operating, and what evidence establishes it?", evidenceObjectives: ["inspect-environment"] },
    { id: "up-but-broken", prompt: "REPORTS-01 answered ping. Why didn't that mean the reporting site was working?", evidenceObjectives: ["confirm-host-up", "confirm-port-closed"] },
    { id: "root-cause", prompt: "What specific evidence explained why the reporting service never came back up?", evidenceObjectives: ["authenticate-reports", "correlate-cause"] },
  ],
  detections: {},
  routes: [],
  blueProfiles: [],
  defaultBlueProfile: "",
};
