import type { ScenarioDefinition } from "./types";
import { commonDetections, discover, external, file, host, identity, link, route } from "./content";

export const somethingCallingHome: ScenarioDefinition = {
  id: "something-calling-home", name: "Operation Something Is Calling Home", organization: "Halcyon Utilities",
  presentation: { caseId: "IR-21", order: 8, prerequisite: "strange-login", focus: ["Beaconing", "Persistence", "Operational safety"] },
  briefing: { red: "Halcyon's outage dashboard and contractor gateway both reach the protected switching schedule. Retrieve SWITCH_WINDOW.csv while preserving a path for persistent access.", blue: "A new periodic process appeared near a contractor access window. Contain the data path and remove persistence without disrupting outage coordination.", constraints: ["A periodic process requires process and startup-artifact correlation", "Outage coordination must remain available"] },
  availableModes: ["RED", "BLUE"], assistance: { guided: ["The dashboard worker can execute as root; install-agent makes the periodic beacon explicit.", "The contractor gateway uses a valid switching identity, but not for interactive schedule export.", "Removing an agent and blocking a connection solve different parts of the incident."], operator: "Separate beacon behavior from the credential path it enables, then contain both with the least operational disruption." },
  conditions: { timeLimitMinutes: 90, minimumAvailability: 60 }, aliases: { "outages.halcyon.test": "OUTAGE-WEB" }, startingKnowledge: { knownHosts: ["INTERNET", "OUTAGE-WEB"], knownAssets: ["outages.halcyon.test"] },
  machines: [external, host("OUTAGE-WEB", "10.90.1.10", "DMZ", [identity("root", "ROOT")], [file("/etc/halcyon/dashboard.conf", "root", "SCHEDULE_HOST=SCHEDULE-01\nUSER=switch_svc\nTOKEN=halcyon-switch")], true), host("CONTRACTOR-01", "10.90.1.30", "DMZ", [identity("ravi")], [file("/home/ravi/switching.txt", "ravi", "Contractor handoff reaches SCHEDULE-01 using switch_svc. Interactive export is not part of the field handoff.")]), host("SCHEDULE-01", "10.90.2.10", "INTERNAL", [identity("switch_svc", "SERVICE")], [file("/srv/grid/SWITCH_WINDOW.csv", "switch_svc", "SIMULATED GRID SCHEDULE\nwindow,substation\n03:00,H-17")]), host("DISPATCH-01", "10.90.2.30", "INTERNAL", [identity("dispatch_svc", "SERVICE")])],
  connections: [link("INTERNET", "OUTAGE-WEB", 443), link("INTERNET", "CONTRACTOR-01", 22, "CONTRACTOR_LOGIN"), link("OUTAGE-WEB", "SCHEDULE-01", 22, "DASHBOARD_SCHEDULE_LOGIN"), link("CONTRACTOR-01", "SCHEDULE-01", 22, "CONTRACTOR_SCHEDULE_LOGIN"), link("DISPATCH-01", "SCHEDULE-01", 22)],
  discoveries: [{ trigger: { kind: "web", host: "OUTAGE-WEB", value: "outages.halcyon.test" }, output: "Halcyon outage dashboard\nField handoff: ravi@CONTRACTOR-01 / HalcyonField-17\nDashboard reconciliation worker enabled.", hosts: ["CONTRACTOR-01"], credentials: [{ username: "ravi", scope: "CONTRACTOR-01" }] }, discover("OUTAGE-WEB", "/etc/halcyon/dashboard.conf", "SCHEDULE-01", "switch_svc"), discover("CONTRACTOR-01", "/home/ravi/switching.txt", "SCHEDULE-01", "switch_svc")],
  webInteractions: [{ host: "OUTAGE-WEB", method: "POST", path: "/dashboard/reconcile", dataIncludes: "outage=external", sessionUser: "root", prerequisiteAction: "PORT_PROBE", output: "The reconciliation worker accepted the public outage update as root. Session opened.", evidence: [{ action: "WEB_WORKER_EXECUTED", category: "WEB", severity: "HIGH" }, { action: "PROCESS_SPAWN", category: "PROCESS", severity: "HIGH" }] }], objectives: [{ id: "switch-window", type: "retrieve_file", host: "SCHEDULE-01", path: "/srv/grid/SWITCH_WINDOW.csv", label: "Retrieve SWITCH_WINDOW.csv" }],
  detections: { ...commonDetections, CONTRACTOR_LOGIN: { id: "AUTH-FIELD-01", title: "Field contractor login", severity: "LOW", rationale: "Field access is expected only during an approved switching handoff." }, DASHBOARD_SCHEDULE_LOGIN: { id: "AUTH-DASH-01", title: "Outage dashboard reached switching schedule", severity: "MEDIUM", rationale: "A public dashboard initiated an interactive schedule session." }, CONTRACTOR_SCHEDULE_LOGIN: { id: "AUTH-FIELD-02", title: "Contractor path reached switching schedule", severity: "HIGH", rationale: "A contractor gateway reused the switching identity beyond its handoff purpose." } },
  routes: [route("dashboard-beacon", "Dashboard beacon", ["INTERNET", "OUTAGE-WEB", "SCHEDULE-01"], "A root dashboard worker stores the switching credential. Persistence creates an observable periodic beacon.", "Did the dashboard worker become a persistent route into switching schedules?", true), route("field-handoff", "Field handoff", ["INTERNET", "CONTRACTOR-01", "SCHEDULE-01"], "A valid contractor handoff trusts the switching identity only for a narrow operational purpose.", "Did a field handoff become an interactive export route?", false)],
  blueProfiles: [{ id: "dashboard-beacon", routeId: "dashboard-beacon", commands: ["nmap OUTAGE-WEB", "curl -X POST outages.halcyon.test/dashboard/reconcile --data outage=external", "install-agent", "cat /etc/halcyon/dashboard.conf", "ssh switch_svc@SCHEDULE-01", "retrieve SWITCH_WINDOW.csv"] }, { id: "field-handoff", routeId: "field-handoff", commands: ["curl outages.halcyon.test", "ssh ravi@CONTRACTOR-01", "cat /home/ravi/switching.txt", "ssh switch_svc@SCHEDULE-01", "retrieve SWITCH_WINDOW.csv"] }], defaultBlueProfile: "dashboard-beacon",
  securityControls: [{ host: "OUTAGE-WEB", telemetry: ["WEB", "NETWORK", "PROCESS", "PERSISTENCE"] }, { host: "CONTRACTOR-01", telemetry: ["AUTH", "NETWORK"] }, { host: "SCHEDULE-01", telemetry: ["AUTH", "FILESYSTEM"] }], businessServices: [{ name: "Outage coordination", hosts: ["OUTAGE-WEB"], impact: "Operators lose outage coordination updates." }, { name: "Switch scheduling", hosts: ["SCHEDULE-01"], impact: "Planned grid work is delayed." }, { name: "Control dispatch", hosts: ["DISPATCH-01"], impact: "Dispatch coordination is degraded." }], persistencePolicy: { process: "outage-health-agent", requiredPrivilege: "ROOT", beaconSeconds: 30 }, knowledgeRewards: [{ concept: "Persistence", actions: ["PERSISTENCE_INSTALLED", "AGENT_BEACON", "REMOVE_PERSISTENCE"] }, { concept: "Incident response", actions: ["BLOCK_CONNECTION", "ATTACK_CONTAINED"] }], backgroundActivity: [{ host: "SCHEDULE-01", source: "DISPATCH-01", user: "switch_svc", action: "AUTH_SUCCESS", context: "Approved dispatch scheduling; no interactive file export." }],
};
