import type { ScenarioDefinition } from "./types";
import { commonDetections, discover, dns, external, file, guidedOnboarding, host, identity, link, route, withObjectiveHints } from "./content";

export const strangeLogin: ScenarioDefinition = {
  id: "strange-login", name: "Operation The Strange Login", organization: "Northline Health",
  presentation: { caseId: "IR-14", order: 11, prerequisite: "paper-trail", focus: ["Identity context", "Clinical access", "Triage"] },
  briefing: { red: "Northline's patient-results system is reachable through a maintenance portal and a legitimate locum-access workflow. Retrieve ON_CALL_ROSTER.csv without interrupting clinical results.", blue: "An unfamiliar source used a valid clinical identity shortly after maintenance activity. Determine whether it is a real on-call workflow or misuse, and stop disclosure without taking results offline.", constraints: ["A valid clinician identity is not proof of legitimate intent", "Clinical results must remain available"] },
  availableModes: ["RED", "BLUE"],
  assistance: { guided: guidedOnboarding, operator: "Correlate a valid identity with source, timing, target, and business purpose before choosing containment." },
  conditions: { timeLimitMinutes: 90, minimumAvailability: 60 }, dnsRecords: dns({ "care.northline.test": "CARE-PORTAL" }), startingKnowledge: { knownHosts: ["INTERNET", "CARE-PORTAL"], knownAssets: ["care.northline.test"] },
  machines: [external,
    host("CARE-PORTAL", "10.80.1.10", "DMZ", [identity("root", "ROOT")], [file("/etc/northline/maintenance.conf", "root", "RESULTS_HOST=RESULTS-01\nUSER=results_svc\nTOKEN=northline-results")], true),
    host("LOCUM-ACCESS", "10.80.1.30", "DMZ", [identity("dana")], [file("/home/dana/on-call.txt", "dana", "Locum access reaches RESULTS-01 as results_svc for approved coverage. Export path: /srv/clinical/ON_CALL_ROSTER.csv")]),
    host("RESULTS-01", "10.80.2.10", "INTERNAL", [identity("results_svc", "SERVICE")], [file("/srv/clinical/ON_CALL_ROSTER.csv", "results_svc", "SIMULATED CLINICAL ROSTER\nteam,coverage\nNorthline ED,overnight")]),
    host("LAB-01", "10.80.2.30", "INTERNAL", [identity("lab_svc", "SERVICE")]),
  ],
  connections: [link("INTERNET", "CARE-PORTAL", 443), link("INTERNET", "LOCUM-ACCESS", 22, "LOCUM_LOGIN"), link("CARE-PORTAL", "RESULTS-01", 22, "MAINTENANCE_RESULTS_LOGIN"), link("LOCUM-ACCESS", "RESULTS-01", 22, "LOCUM_RESULTS_LOGIN"), link("LAB-01", "RESULTS-01", 22)],
  discoveries: [{ trigger: { kind: "web", host: "CARE-PORTAL", value: "care.northline.test" }, output: "Northline Care Portal\nLocum coverage: dana@LOCUM-ACCESS / NorthlineCover-41\nMaintenance worker enabled for results reconciliation.", hosts: ["LOCUM-ACCESS"], credentials: [{ username: "dana", scope: "LOCUM-ACCESS" }] }, discover("CARE-PORTAL", "/etc/northline/maintenance.conf", "RESULTS-01", "results_svc"), discover("LOCUM-ACCESS", "/home/dana/on-call.txt", "RESULTS-01", "results_svc")],
  webInteractions: [{ host: "CARE-PORTAL", method: "POST", path: "/maintenance/reconcile", dataIncludes: "source=external", sessionUser: "root", prerequisiteAction: "PORT_PROBE", output: "The maintenance worker accepted the unsigned reconciliation request as root. Session opened.", evidence: [{ action: "WEB_WORKER_EXECUTED", category: "WEB", severity: "HIGH" }, { action: "PROCESS_SPAWN", category: "PROCESS", severity: "HIGH" }] }],
  objectives: withObjectiveHints("strange-login", [{ id: "on-call-roster", type: "retrieve_file", host: "RESULTS-01", path: "/srv/clinical/ON_CALL_ROSTER.csv", label: "Retrieve ON_CALL_ROSTER.csv" }]),
  detections: { ...commonDetections, LOCUM_LOGIN: { id: "AUTH-LOCUM-01", title: "Locum clinician login", severity: "LOW", rationale: "On-call access is legitimate only when source, shift, and clinical purpose agree." }, MAINTENANCE_RESULTS_LOGIN: { id: "AUTH-MAINT-01", title: "Maintenance worker reached clinical results", severity: "MEDIUM", rationale: "A public-facing maintenance worker opened an interactive results session." }, LOCUM_RESULTS_LOGIN: { id: "AUTH-LOCUM-02", title: "Locum access reached results", severity: "HIGH", rationale: "A remote clinician path reused the service identity outside the on-call context." } },
  routes: [route("maintenance-worker", "Maintenance worker", ["INTERNET", "CARE-PORTAL", "RESULTS-01"], "A privileged reconciliation worker holds the results credential. Its source is public and its session is conspicuous.", "Did portal maintenance cross into clinical results?", true), route("locum-coverage", "Locum coverage", ["INTERNET", "LOCUM-ACCESS", "RESULTS-01"], "A legitimate locum workflow receives the same results identity, but it is constrained by source and on-call purpose.", "Did valid locum access turn into an inappropriate results export?", false)],
  blueProfiles: [{ id: "maintenance-worker", routeId: "maintenance-worker", commands: ["nmap CARE-PORTAL", "curl -X POST care.northline.test/maintenance/reconcile --data source=external", "cat /etc/northline/maintenance.conf", "ssh results_svc@RESULTS-01", "retrieve ON_CALL_ROSTER.csv"] }, { id: "locum-coverage", routeId: "locum-coverage", commands: ["curl care.northline.test", "ssh dana@LOCUM-ACCESS", "cat /home/dana/on-call.txt", "ssh results_svc@RESULTS-01", "retrieve ON_CALL_ROSTER.csv"] }], defaultBlueProfile: "locum-coverage",
  securityControls: [{ host: "CARE-PORTAL", telemetry: ["WEB", "NETWORK", "PROCESS", "AUTH"] }, { host: "LOCUM-ACCESS", telemetry: ["AUTH", "NETWORK"] }, { host: "RESULTS-01", telemetry: ["AUTH", "FILESYSTEM"] }], businessServices: [{ name: "Care portal", hosts: ["CARE-PORTAL"], impact: "Clinicians cannot view patient intake." }, { name: "Clinical results", hosts: ["RESULTS-01"], impact: "Results review is delayed." }, { name: "Lab integration", hosts: ["LAB-01"], impact: "Lab result delivery is delayed." }],
  persistencePolicy: { process: "care-maintenance-agent", requiredPrivilege: "ROOT", beaconSeconds: 30 }, knowledgeRewards: [{ concept: "Identity correlation", actions: ["LOCUM_LOGIN", "LOCUM_RESULTS_LOGIN", "INSPECT_USER"] }, { concept: "Incident response", actions: ["BLOCK_CONNECTION", "ATTACK_CONTAINED"] }], backgroundActivity: [{ host: "RESULTS-01", source: "LAB-01", user: "results_svc", action: "AUTH_SUCCESS", context: "Approved lab integration; scheduled result delivery with no interactive export." }, { host: "LOCUM-ACCESS", user: "dana", action: "AUTH_SUCCESS", context: "Approved locum access during overnight coverage; results export requires an assigned clinical case." }],
};
