import { AccessLevel, NetworkZone } from "@/app/generated/prisma/enums";
import type { ScenarioDefinition } from "./types";
import { dns, guidedOnboarding, service, withObjectiveHints } from "./content";

const learning = (
  concepts: string[],
  evidence: string,
  domain: "COMPUTING_OS" | "NETWORKING" | "SECURITY_REASONING" = "NETWORKING",
): NonNullable<ScenarioDefinition["objectives"][number]["learning"]> => ({
  domain,
  concepts,
  stage: "PRACTICED",
  evidence,
});

export const theNewServer: ScenarioDefinition = {
  id: "the-new-server",
  name: "The New Server",
  organization: "Nodeline Security",
  briefing: {
    red: "Operations provisioned a new client-facing host for tomorrow's launch. Verify it is correctly addressed, reachable, and running the expected service before sign-off, then retrieve the go-live checklist.",
    blue: "This orientation assignment has no defensive role.",
    constraints: ["Use the bounded ROOT/OS terminal", "Treat command output and local documentation as evidence", "Confirm every part of the provisioning record independently before signing off"],
  },
  objectiveSummary: "Independently verify a new host's address, reachability, and exposed service before commissioning it",
  presentation: { caseId: "NET-04", focus: ["IP addressing", "Hosts", "Ports and services", "SSH"], order: 6, prerequisite: "wrong-network" },
  availableModes: ["RED"],
  assistance: {
    guided: guidedOnboarding,
    operator: "Use the provisioning ticket as your only procedure. Verify address, reachability, and exposed service independently before signing off.",
    operatorAvailableAtStart: true,
  },
  conditions: { timeLimitMinutes: 25, minimumAvailability: 100 },
  securityControls: [{ host: "HELPDESK-01", telemetry: ["SYSTEM", "FILESYSTEM"] }, { host: "NEW-APP-01", telemetry: ["NETWORK", "WEB", "AUTH", "FILESYSTEM"] }],
  businessServices: [{ name: "New client application", hosts: ["NEW-APP-01"], impact: "Tomorrow's client launch cannot be signed off without commissioning verification." }],
  persistencePolicy: { process: "helpdesk-agent", requiredPrivilege: AccessLevel.ROOT, beaconSeconds: 60 },
  knowledgeRewards: [],
  backgroundActivity: [],
  dnsRecords: dns({ "helpdesk-01.nodeline.test": "HELPDESK-01", "newapp.nodeline.test": "NEW-APP-01" }),
  startingKnowledge: { knownHosts: ["HELPDESK-01"], knownAssets: [] },
  startingSession: { host: "HELPDESK-01", user: "trainee", path: "/home/trainee" },
  facts: [
    {
      id: "newserver.ticket",
      category: "NETWORK",
      known: "A new client application host was provisioned. Its provisional IP, 10.0.0.90, was reassigned to 10.0.0.91 after an address conflict.",
      unknown: "Which address is actually live, and what the host is actually running",
      guidance: "Read the provisioning ticket before touching the network.",
      discoverableFrom: "/home/trainee/TICKET-5300.txt",
      requiredFor: "Scoping the commissioning check to the correct address",
    },
    {
      id: "newserver.confirmedAddress",
      category: "NETWORK",
      known: "10.0.0.91 (NEW-APP-01) is live; 10.0.0.90 was never assigned to a host.",
      unknown: "Whether the provisional or reassigned address is the one to verify",
      guidance: "Ping both candidate addresses before trusting either one.",
      discoverableFrom: "ping output for 10.0.0.90 and 10.0.0.91",
      requiredFor: "Verifying the host's address independently rather than assuming the ticket is current",
    },
    {
      id: "newserver.portsConfirmed",
      category: "NETWORK",
      known: "NEW-APP-01 exposes SSH and HTTPS, matching the provisioning record.",
      unknown: "Whether the host is actually running the services the ticket claims",
      guidance: "Scan the live address to confirm what is actually open.",
      discoverableFrom: "nmap output for NEW-APP-01",
      requiredFor: "Verifying exposed services independently rather than trusting the record",
    },
    {
      id: "newserver.appConfirmed",
      category: "APPLICATION",
      known: "NEW-APP-01 serves the expected client application over HTTPS.",
      unknown: "Whether the running web service is actually the correct application",
      guidance: "Curl the host directly and read the response.",
      discoverableFrom: "HTTP response from NEW-APP-01",
      requiredFor: "Confirming the correct application before sign-off",
    },
    {
      id: "newserver.commissioningAccess",
      category: "IDENTITY",
      known: "A commissioning credential is documented for signing off newly provisioned hosts.",
      unknown: "The username and password needed to log in to NEW-APP-01",
      guidance: "Read the commissioning access note before trying to guess a login.",
      discoverableFrom: "/home/trainee/COMMISSIONING_ACCESS.txt",
      requiredFor: "Logging in to retrieve the go-live checklist",
    },
  ],
  machines: [
    {
      hostname: "HELPDESK-01",
      ip: "10.0.0.20",
      zone: NetworkZone.INTERNAL,
      os: "linux",
      users: [
        { username: "trainee", role: "operator_trainee", privilege: AccessLevel.USER, groups: ["trainees", "operations"] },
        { username: "root", role: "administrator", privilege: AccessLevel.ROOT, groups: ["root"] },
      ],
      services: [],
      files: [
        {
          path: "/home/trainee/TICKET-5300.txt",
          owner: "trainee",
          group: "trainees",
          permissions: "640",
          isSecret: false,
          contents: [
            "TICKET 5300 // New host commissioning",
            "",
            "A new client-facing application host was provisioned for tomorrow's launch.",
            "Provisional IP 10.0.0.90 was reassigned to 10.0.0.91 after an address conflict during setup.",
            "Verify the address, confirm the host is reachable, confirm it exposes only the expected services, confirm it serves the correct application, and sign off with evidence.",
          ].join("\n"),
        },
        {
          path: "/home/trainee/COMMISSIONING_ACCESS.txt",
          owner: "trainee",
          group: "trainees",
          permissions: "640",
          isSecret: false,
          contents: [
            "HELPDESK // Commissioning access",
            "",
            "Newly provisioned hosts accept the standard commissioning credential until handed off to their owning team:",
            "  user: commissioning",
            "  password: SignOff-2026",
          ].join("\n"),
        },
      ],
      processes: [{ name: "sshd", pid: 130, runningAs: "root", commandLine: "/usr/sbin/sshd -D" }],
    },
    {
      hostname: "NEW-APP-01",
      ip: "10.0.0.91",
      zone: NetworkZone.INTERNAL,
      os: "linux",
      users: [
        { username: "commissioning", role: "commissioning_access", privilege: AccessLevel.USER, groups: ["commissioning"], password: "SignOff-2026" },
        { username: "app-svc", role: "app_service", privilege: AccessLevel.SERVICE, groups: ["app-svc"] },
        { username: "root", role: "administrator", privilege: AccessLevel.ROOT, groups: ["root"] },
      ],
      services: [service("ssh", 22, "root", [NetworkZone.INTERNAL]), service("https", 443, "app-svc", [NetworkZone.INTERNAL])],
      files: [
        {
          path: "/srv/app/GO_LIVE_CHECKLIST.txt",
          owner: "commissioning",
          group: "commissioning",
          permissions: "640",
          isSecret: false,
          contents: "GO-LIVE CHECKLIST: address verified, host reachable, only SSH and HTTPS exposed, application responds correctly. Approved for launch.",
        },
      ],
      processes: [
        { name: "sshd", pid: 160, runningAs: "root", commandLine: "/usr/sbin/sshd -D" },
        { name: "client-app-worker", pid: 620, runningAs: "app-svc", commandLine: "/usr/sbin/client-app-worker --port 443" },
      ],
    },
  ],
  connections: [
    { source: "HELPDESK-01", target: "NEW-APP-01", port: 22 },
    { source: "HELPDESK-01", target: "NEW-APP-01", port: 443 },
  ],
  httpRoutes: [
    { host: "NEW-APP-01", method: "POST", path: "/login", login: { usernameField: "username", passwordField: "password" }, output: "HTTP/1.1 200 OK\nSet-Cookie: session=new-app-01\n\nLogged in.", invalidOutput: "HTTP/1.1 401 Unauthorized\nInvalid credentials." },
    { host: "NEW-APP-01", method: "GET", path: "/account", requiresSession: true, output: "HTTP/1.1 200 OK\n\nCommissioning account: launch checklist pending sign-off.", unauthorizedOutput: "HTTP/1.1 401 Unauthorized\nLog in first." },
  ],
  discoveries: [
    { trigger: { kind: "file", host: "HELPDESK-01", value: "/home/trainee/TICKET-5300.txt" }, hosts: ["NEW-APP-01"], facts: ["newserver.ticket"] },
    { trigger: { kind: "file", host: "HELPDESK-01", value: "/home/trainee/COMMISSIONING_ACCESS.txt" }, facts: ["newserver.commissioningAccess"], credentials: [{ username: "commissioning", scope: "NEW-APP-01" }] },
    { trigger: { kind: "scan", host: "NEW-APP-01", value: "ssh" }, facts: ["newserver.confirmedAddress"] },
    { trigger: { kind: "scan", host: "NEW-APP-01", value: "https" }, facts: ["newserver.portsConfirmed"] },
    { trigger: { kind: "web", host: "NEW-APP-01", value: "newapp.nodeline.test" }, output: "HTTP/1.1 200 OK\n\nWelcome — Client Application\nBuild verified for launch.", facts: ["newserver.appConfirmed"] },
  ],
  objectives: withObjectiveHints("the-new-server", [
    { id: "locate-session", type: "event", label: "Establish the current directory", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "CURRENT_DIRECTORY" } }, learning: learning(["Files and directories", "Command-line navigation"], "Observed the active shell working directory with pwd.", "COMPUTING_OS") },
    { id: "identify-user", type: "event", label: "Identify the current user", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "CURRENT_USER" } }, learning: learning(["Users"], "Observed the session username with whoami.", "COMPUTING_OS") },
    { id: "inspect-groups", type: "event", label: "Inspect identity and group membership", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "IDENTITY_GROUPS" } }, learning: learning(["Users and groups"], "Observed identity, privilege, and group membership with id.", "COMPUTING_OS") },
    { id: "inspect-environment", type: "event", label: "Inspect the session environment", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "ENVIRONMENT" } }, learning: learning(["Environment variables", "Current host"], "Observed host and session context through environment variables.", "COMPUTING_OS") },
    { id: "review-ticket", type: "fact", factId: "newserver.ticket", label: "Read the provisioning ticket", learning: learning(["Documentation", "IP addresses"], "Read the provisioning ticket and identified two candidate addresses to verify independently.", "SECURITY_REASONING") },
    { id: "confirm-address", type: "fact", factId: "newserver.confirmedAddress", label: "Confirm which address is actually live", learning: learning(["IP addresses", "Hosts", "Reachability"], "Pinged and scanned the candidate addresses and confirmed which one is actually assigned, rather than trusting the ticket alone.", "SECURITY_REASONING") },
    { id: "confirm-ports", type: "fact", factId: "newserver.portsConfirmed", label: "Confirm the exposed services independently", learning: learning(["Ports", "Services"], "Scanned NEW-APP-01 and confirmed it exposes only the expected SSH and HTTPS services.") },
    { id: "confirm-app", type: "fact", factId: "newserver.appConfirmed", label: "Confirm the correct application is running", learning: learning(["HTTP basics", "Services"], "Curled the host directly and confirmed it serves the expected client application.") },
    { id: "discover-commissioning-access", type: "fact", factId: "newserver.commissioningAccess", label: "Find the commissioning credential", learning: learning(["Users", "SSH", "Documentation"], "Identified the documented commissioning credential rather than guessing one.", "SECURITY_REASONING") },
    { id: "authenticate-newapp", type: "event", label: "Log in to NEW-APP-01", event: { action: "SESSION_CREATED", targetHost: "NEW-APP-01", userId: "commissioning" }, learning: learning(["SSH", "Users"], "Authenticated to NEW-APP-01 using the documented commissioning credential.") },
    { id: "retrieve-checklist", type: "retrieve_file", host: "NEW-APP-01", path: "/srv/app/GO_LIVE_CHECKLIST.txt", label: "Retrieve GO_LIVE_CHECKLIST.txt", learning: learning(["Evidence versus assumptions"], "Retrieved the go-live checklist only after independently verifying address, reachability, and exposed service.", "SECURITY_REASONING") },
  ]),
  objectiveCompletion: "ALL",
  beginnerExitQuestions: [
    { id: "current-host", prompt: "What host are you operating, and what evidence establishes it?", evidenceObjectives: ["inspect-environment"] },
    { id: "address-verification", prompt: "The ticket listed two candidate IPs. How did you determine which one was actually live?", evidenceObjectives: ["confirm-address"] },
    { id: "service-verification", prompt: "What evidence confirmed the host exposed only the expected services and ran the expected application?", evidenceObjectives: ["confirm-ports", "confirm-app"] },
    { id: "evidence-outcome", prompt: "What confirms you signed off on this host with evidence rather than assuming the ticket was accurate?", evidenceObjectives: ["retrieve-checklist"] },
  ],
  detections: {},
  routes: [],
  blueProfiles: [],
  defaultBlueProfile: "",
};
