import { AccessLevel, NetworkZone } from "@/app/generated/prisma/enums";
import type { ScenarioDefinition } from "./types";
import { dns } from "./content";

const learning = (
  concepts: string[],
  evidence: string,
  domain: "COMPUTING_OS" | "SECURITY_REASONING" = "COMPUTING_OS",
): NonNullable<ScenarioDefinition["objectives"][number]["learning"]> => ({
  domain,
  concepts,
  stage: "PRACTICED",
  evidence,
});

export const thePrinter: ScenarioDefinition = {
  id: "the-printer",
  name: "The Printer",
  organization: "Nodeline Security",
  briefing: {
    red: "Floor 2 reports the print queue has been stuck since 09:14. Investigate HELPDESK-01 and determine the root cause using only evidence available on the host.",
    blue: "This orientation assignment has no defensive role.",
    constraints: ["Use the bounded ROOT/OS terminal", "Treat command output and local documentation as evidence", "Do not report a cause without evidence, even if the ticket suggests one"],
  },
  objectiveSummary: "Diagnose the print queue failure from process, log, and permission evidence",
  presentation: { caseId: "NDL-01", focus: ["Processes", "Logs", "Permissions and groups"], order: 1, prerequisite: "first-shift" },
  availableModes: ["RED"],
  assistance: {
    guided: [
      "Start with the ticket in your home directory, then confirm whether the reported service is actually stopped before assuming it is.",
      "A process still running does not mean nothing is wrong. Read its log file for the actual error rather than guessing.",
      "Compare the failing resource's owner and group permissions against the group membership reference before concluding why access fails.",
    ],
    operator: "Use the trouble ticket, the spooler log, and the group membership reference as your only procedure. State the cause only from what the evidence shows.",
    operatorAvailableAtStart: true,
  },
  conditions: { timeLimitMinutes: 20, minimumAvailability: 100 },
  securityControls: [{ host: "HELPDESK-01", telemetry: ["SYSTEM", "FILESYSTEM", "PROCESS"] }],
  businessServices: [{ name: "Print services", hosts: ["HELPDESK-01"], impact: "Floor 2 cannot print onboarding paperwork." }],
  persistencePolicy: { process: "helpdesk-agent", requiredPrivilege: AccessLevel.ROOT, beaconSeconds: 60 },
  knowledgeRewards: [],
  backgroundActivity: [],
  dnsRecords: dns({ "helpdesk-01.nodeline.test": "HELPDESK-01" }),
  startingKnowledge: { knownHosts: ["HELPDESK-01"], knownAssets: [] },
  startingSession: { host: "HELPDESK-01", user: "trainee", path: "/home/trainee" },
  facts: [
    {
      id: "printer.ticket",
      category: "HOST",
      known: "Floor 2's print queue has been stuck since 09:14 with no client-side error.",
      unknown: "What is actually failing on HELPDESK-01",
      guidance: "Read the trouble ticket before touching the spooler.",
      discoverableFrom: "/home/trainee/TICKET-4471.txt",
      requiredFor: "Scoping the investigation to the reported service",
    },
    {
      id: "printer.processState",
      category: "HOST",
      known: "print-spoolerd is running as printsvc and has not crashed.",
      unknown: "Whether the service process itself is the failure",
      guidance: "Compare the running process table with the ticket's assumption that the service is down.",
      discoverableFrom: "ps output for print-spoolerd",
      requiredFor: "Ruling out a crashed service before investigating further",
    },
    {
      id: "printer.logEvidence",
      category: "HOST",
      known: "print-spoolerd logs repeated permission-denied errors writing to /var/spool/printer.",
      unknown: "Why queued jobs never complete despite the service running",
      guidance: "Read or grep the spooler log for ERROR entries.",
      discoverableFrom: "/var/log/print-spooler.log",
      requiredFor: "Root-causing the failure from evidence rather than assumption",
    },
    {
      id: "printer.groupMismatch",
      category: "IDENTITY",
      known: "printsvc is not a member of the print group that /var/spool/printer's permissions require for write access.",
      unknown: "Why a running, correctly-owned process still cannot write to its own spool directory",
      guidance: "Compare the spool directory's group ownership and mode against the group membership reference.",
      discoverableFrom: "/etc/nodeline/group-membership.txt",
      requiredFor: "Explaining the failure as a group relationship rather than a crash",
    },
  ],
  machines: [{
    hostname: "HELPDESK-01",
    ip: "10.0.0.20",
    zone: NetworkZone.INTERNAL,
    os: "linux",
    users: [
      { username: "trainee", role: "operator_trainee", privilege: AccessLevel.USER, groups: ["trainees", "operations"] },
      { username: "lead", role: "shift_lead", privilege: AccessLevel.USER, groups: ["operations", "print"] },
      { username: "printsvc", role: "print_service", privilege: AccessLevel.SERVICE, groups: ["printsvc"] },
      { username: "root", role: "administrator", privilege: AccessLevel.ROOT, groups: ["root"] },
    ],
    services: [],
    files: [
      {
        path: "/home/trainee/TICKET-4471.txt",
        owner: "trainee",
        group: "trainees",
        permissions: "640",
        isSecret: false,
        contents: [
          "TICKET 4471 // Floor 2 print queue",
          "",
          "Reported: queue stuck since 09:14. No error dialog on client machines.",
          "Investigate the spooler service on HELPDESK-01 and record the root cause using evidence, not assumption.",
        ].join("\n"),
      },
      {
        path: "/var/log/print-spooler.log",
        owner: "root",
        group: "sysadmin",
        permissions: "644",
        isSecret: false,
        contents: [
          "2026-09-18 09:14:02 print-spoolerd[701]: INFO queue job 5521 accepted",
          "2026-09-18 09:14:03 print-spoolerd[701]: ERROR permission denied writing /var/spool/printer/5521.spool (uid=printsvc gid=printsvc)",
          "2026-09-18 09:14:03 print-spoolerd[701]: ERROR job 5521 requeued",
        ].join("\n"),
      },
      {
        path: "/etc/nodeline/group-membership.txt",
        owner: "root",
        group: "operations",
        permissions: "644",
        isSecret: false,
        contents: [
          "NODELINE GROUP MEMBERSHIP (reference)",
          "",
          "print: helpdesk, lead",
          "operations: trainee, lead",
          "sysadmin: root",
          "",
          "printsvc is not listed under any group besides its own default group printsvc.",
        ].join("\n"),
      },
      {
        path: "/var/spool/printer",
        owner: "root",
        group: "print",
        permissions: "770",
        isSecret: false,
        contents: "Queued print jobs for Floor 2.",
      },
    ],
    processes: [
      { name: "sshd", pid: 140, runningAs: "root", commandLine: "/usr/sbin/sshd -D" },
      { name: "print-spoolerd", pid: 701, runningAs: "printsvc", commandLine: "/usr/sbin/print-spoolerd --queue /var/spool/printer" },
    ],
  }],
  connections: [],
  discoveries: [
    { trigger: { kind: "file", host: "HELPDESK-01", value: "/home/trainee/TICKET-4471.txt" }, facts: ["printer.ticket"] },
    { trigger: { kind: "process", host: "HELPDESK-01", value: "print-spoolerd" }, facts: ["printer.processState"] },
    { trigger: { kind: "file", host: "HELPDESK-01", value: "/var/log/print-spooler.log" }, facts: ["printer.logEvidence"] },
    { trigger: { kind: "file", host: "HELPDESK-01", value: "/etc/nodeline/group-membership.txt" }, facts: ["printer.groupMismatch"] },
  ],
  objectives: [
    { id: "locate-session", type: "event", label: "Establish the current directory", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "CURRENT_DIRECTORY" } }, learning: learning(["Files and directories", "Command-line navigation"], "Observed the active shell working directory with pwd.") },
    { id: "identify-user", type: "event", label: "Identify the current user", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "CURRENT_USER" } }, learning: learning(["Users"], "Observed the session username with whoami.") },
    { id: "inspect-groups", type: "event", label: "Inspect identity and group membership", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "IDENTITY_GROUPS" } }, learning: learning(["Users and groups", "Permissions"], "Observed identity, privilege, and group membership with id.") },
    { id: "inspect-environment", type: "event", label: "Inspect the session environment", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "ENVIRONMENT" } }, learning: learning(["Environment variables", "Current host"], "Observed host and session context through environment variables.") },
    { id: "review-ticket", type: "fact", factId: "printer.ticket", label: "Read the trouble ticket", learning: learning(["Documentation", "Evidence versus assumptions"], "Read the trouble ticket and scoped the investigation to the reported service.", "SECURITY_REASONING") },
    { id: "inspect-process", type: "fact", factId: "printer.processState", label: "Confirm the service process is running", learning: learning(["Processes", "Services"], "Correlated the process table with the ticket's assumption that the service had crashed.") },
    { id: "inspect-log", type: "fact", factId: "printer.logEvidence", label: "Find the error in the service log", learning: learning(["Documentation", "Evidence versus assumptions"], "Read the spooler log and identified the actual error rather than assuming a cause.", "SECURITY_REASONING") },
    { id: "inspect-spool-permissions", type: "event", label: "Inspect the spool directory's ownership and permissions", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "DIRECTORY_LISTING", path: "/var/spool/printer", detailed: true } }, learning: learning(["Files and directories", "Permissions"], "Used a long directory listing to observe the spool directory's owner, group, and permission digits.") },
    { id: "correlate-cause", type: "fact", factId: "printer.groupMismatch", label: "Explain the failure as a group membership mismatch", learning: learning(["Users and groups", "Permissions"], "Correlated the spool directory's group requirement with the service account's group membership to explain the failure.", "SECURITY_REASONING") },
  ],
  objectiveCompletion: "ALL",
  beginnerExitQuestions: [
    { id: "current-host", prompt: "What host are you operating, and what evidence establishes it?", evidenceObjectives: ["inspect-environment"] },
    { id: "current-user", prompt: "Which user and groups define this session?", evidenceObjectives: ["identify-user", "inspect-groups"] },
    { id: "service-state", prompt: "Was the print service actually down? What evidence supports your answer?", evidenceObjectives: ["review-ticket", "inspect-process"] },
    { id: "root-cause", prompt: "What specific error explains why queued jobs never printed?", evidenceObjectives: ["inspect-log"] },
    { id: "permission-relationship", prompt: "How do the spool directory's owner, group, and mode relate to printsvc's group membership?", evidenceObjectives: ["inspect-spool-permissions", "correlate-cause"] },
  ],
  detections: {},
  routes: [],
  blueProfiles: [],
  defaultBlueProfile: "",
};
