import { AccessLevel, NetworkZone } from "@/app/generated/prisma/enums";
import type { ScenarioDefinition } from "./types";
import { dns, service } from "./content";

const learning = (
  concepts: string[],
  evidence: string,
  domain: "COMPUTING_OS" | "NETWORKING" | "SECURITY_REASONING" = "NETWORKING",
): NonNullable<ScenarioDefinition["objectives"][number]["learning"]> => ({
  domain,
  concepts,
  stage: "PRACTICED",
  evidence,
});

export const websiteDown: ScenarioDefinition = {
  id: "website-down",
  name: "Where Did the Website Go?",
  organization: "Nodeline Security",
  briefing: {
    red: "The internal employee intranet has stopped loading for Floor 2. Determine whether the site is actually down or whether something else is wrong, and reach the real site using only evidence you find.",
    blue: "This orientation assignment has no defensive role.",
    constraints: ["Use the bounded ROOT/OS terminal", "Treat command output and local documentation as evidence", "Confirm a host is actually unreachable before assuming a hostname is broken", "Query the DNS record itself rather than assuming what a hostname resolves to"],
  },
  objectiveSummary: "Diagnose a stale hostname record and reach the intranet's current host",
  presentation: { caseId: "NET-01", focus: ["IP addresses and hosts", "DNS", "HTTP basics"], order: 3, prerequisite: "locked-out" },
  availableModes: ["RED"],
  assistance: {
    guided: [
      "Read the ticket, then try reaching the intranet by its usual name before assuming the server itself is broken.",
      "Query the DNS record for the reported hostname directly with dig or nslookup, rather than assuming what it resolves to.",
      "A host answering ping is not the same as a host running a website. Scan it before deciding what's actually wrong.",
      "Read the migration notice in your home directory for where the site actually lives now, then reach it directly.",
    ],
    operator: "Use the trouble ticket and the migration notice as your only procedure. Confirm what a host is actually running before concluding it is down.",
    operatorAvailableAtStart: true,
  },
  conditions: { timeLimitMinutes: 20, minimumAvailability: 100 },
  securityControls: [{ host: "HELPDESK-01", telemetry: ["SYSTEM", "FILESYSTEM"] }, { host: "OLD-INTRANET-01", telemetry: ["NETWORK"] }, { host: "INTRANET-02", telemetry: ["NETWORK", "WEB"] }],
  businessServices: [{ name: "Employee intranet", hosts: ["INTRANET-02"], impact: "Floor 2 cannot reach internal announcements or forms." }],
  persistencePolicy: { process: "helpdesk-agent", requiredPrivilege: AccessLevel.ROOT, beaconSeconds: 60 },
  knowledgeRewards: [],
  backgroundActivity: [],
  dnsRecords: dns({
    "helpdesk-01.nodeline.test": "HELPDESK-01",
    "intranet.nodeline.test": "OLD-INTRANET-01",
    "intranet-new.nodeline.test": "INTRANET-02",
  }),
  startingKnowledge: { knownHosts: ["HELPDESK-01"], knownAssets: [] },
  startingSession: { host: "HELPDESK-01", user: "trainee", path: "/home/trainee" },
  facts: [
    {
      id: "website.ticket",
      category: "NETWORK",
      known: "Floor 2 reports intranet.nodeline.test has stopped loading since this morning.",
      unknown: "Whether the intranet server itself is down or something else has changed",
      guidance: "Read the trouble ticket before touching the network.",
      discoverableFrom: "/home/trainee/TICKET-5102.txt",
      requiredFor: "Scoping the investigation to the reported hostname",
    },
    {
      id: "website.dnsRecordStale",
      category: "NETWORK",
      known: "The DNS record for intranet.nodeline.test is an A record currently pointing at OLD-INTRANET-01 (10.0.0.55).",
      unknown: "Whether that record actually reflects the intranet's current location",
      guidance: "Query the DNS record for intranet.nodeline.test directly with dig or nslookup instead of assuming where it resolves.",
      discoverableFrom: "dig output for intranet.nodeline.test",
      requiredFor: "Confirming exactly what host the hostname currently resolves to before investigating that host",
    },
    {
      id: "website.hostUpNoSite",
      category: "NETWORK",
      known: "intranet.nodeline.test resolves to OLD-INTRANET-01, which is reachable but exposes only SSH, no web service.",
      unknown: "Why a reachable host is not serving the site",
      guidance: "Scan the host the hostname currently points to before assuming the whole intranet is offline.",
      discoverableFrom: "nmap output for OLD-INTRANET-01",
      requiredFor: "Ruling out a total outage in favor of a stale hostname record",
    },
    {
      id: "website.migrationNotice",
      category: "NETWORK",
      known: "The intranet was migrated from OLD-INTRANET-01 (10.0.0.55) to INTRANET-02 (10.0.0.56, intranet-new.nodeline.test). Network-wide hostname records have not been updated yet.",
      unknown: "Where the live intranet actually runs now",
      guidance: "Read the migration notice in your home directory.",
      discoverableFrom: "/home/trainee/DNS_MIGRATION_NOTICE.txt",
      requiredFor: "Reaching the live intranet instead of the retired host",
    },
    {
      id: "website.confirmedLive",
      category: "NETWORK",
      known: "intranet-new.nodeline.test serves the current employee intranet from INTRANET-02.",
      unknown: "Confirmation that the migrated hostname actually serves the site",
      guidance: "Curl the corrected hostname directly.",
      discoverableFrom: "HTTP response from INTRANET-02",
      requiredFor: "Closing the ticket with evidence rather than assumption",
    },
  ],
  machines: [
    {
      hostname: "HELPDESK-01",
      ip: "10.0.0.20",
      zone: NetworkZone.INTERNAL,
      os: "linux",
      users: [
        { username: "trainee", role: "operator_trainee", privilege: AccessLevel.USER, groups: ["trainees", "operations"] },
        { username: "root", role: "administrator", privilege: AccessLevel.ROOT, groups: ["root"] },
      ],
      services: [],
      files: [
        {
          path: "/home/trainee/TICKET-5102.txt",
          owner: "trainee",
          group: "trainees",
          permissions: "640",
          isSecret: false,
          contents: [
            "TICKET 5102 // Intranet unreachable",
            "",
            "Reported: intranet.nodeline.test has not loaded since this morning for Floor 2.",
            "Determine whether the intranet server is actually down before escalating, and record the cause with evidence.",
          ].join("\n"),
        },
        {
          path: "/home/trainee/DNS_MIGRATION_NOTICE.txt",
          owner: "trainee",
          group: "trainees",
          permissions: "640",
          isSecret: false,
          contents: [
            "NETWORK OPERATIONS // Hostname migration notice",
            "",
            "The employee intranet was migrated from OLD-INTRANET-01 (10.0.0.55) to INTRANET-02 (10.0.0.56).",
            "The new hostname is intranet-new.nodeline.test.",
            "Network-wide hostname records for intranet.nodeline.test have not been updated yet and still point to the retired host.",
            "Until that record is corrected, reach the site with the new hostname or by IP directly.",
          ].join("\n"),
        },
      ],
      processes: [{ name: "sshd", pid: 130, runningAs: "root", commandLine: "/usr/sbin/sshd -D" }],
    },
    {
      hostname: "OLD-INTRANET-01",
      ip: "10.0.0.55",
      zone: NetworkZone.INTERNAL,
      os: "linux",
      users: [{ username: "root", role: "administrator", privilege: AccessLevel.ROOT, groups: ["root"] }],
      services: [service("ssh", 22, "root", [NetworkZone.INTERNAL])],
      files: [],
      processes: [{ name: "sshd", pid: 118, runningAs: "root", commandLine: "/usr/sbin/sshd -D" }],
    },
    {
      hostname: "INTRANET-02",
      ip: "10.0.0.56",
      zone: NetworkZone.INTERNAL,
      os: "linux",
      users: [
        { username: "intranet-svc", role: "web_service", privilege: AccessLevel.SERVICE, groups: ["intranet-svc"] },
        { username: "root", role: "administrator", privilege: AccessLevel.ROOT, groups: ["root"] },
      ],
      services: [service("ssh", 22, "root", [NetworkZone.INTERNAL]), service("https", 443, "intranet-svc", [NetworkZone.INTERNAL])],
      files: [],
      processes: [
        { name: "sshd", pid: 141, runningAs: "root", commandLine: "/usr/sbin/sshd -D" },
        { name: "intranet-worker", pid: 512, runningAs: "intranet-svc", commandLine: "/usr/sbin/intranet-worker --port 443" },
      ],
    },
  ],
  connections: [
    { source: "HELPDESK-01", target: "OLD-INTRANET-01", port: 22 },
    { source: "HELPDESK-01", target: "INTRANET-02", port: 22 },
    { source: "HELPDESK-01", target: "INTRANET-02", port: 443 },
  ],
  discoveries: [
    { trigger: { kind: "file", host: "HELPDESK-01", value: "/home/trainee/TICKET-5102.txt" }, facts: ["website.ticket"] },
    { trigger: { kind: "dns", host: "intranet.nodeline.test", value: "OLD-INTRANET-01" }, facts: ["website.dnsRecordStale"] },
    { trigger: { kind: "scan", host: "OLD-INTRANET-01", value: "ssh" }, facts: ["website.hostUpNoSite"] },
    { trigger: { kind: "file", host: "HELPDESK-01", value: "/home/trainee/DNS_MIGRATION_NOTICE.txt" }, hosts: ["INTRANET-02"], facts: ["website.migrationNotice"] },
    { trigger: { kind: "web", host: "INTRANET-02", value: "intranet-new.nodeline.test" }, output: "HTTP/1.1 200 OK\n\nNodeline Intranet — Home\nAnnouncements, forms, and directory.", facts: ["website.confirmedLive"] },
  ],
  objectives: [
    { id: "locate-session", type: "event", label: "Establish the current directory", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "CURRENT_DIRECTORY" } }, learning: learning(["Files and directories", "Command-line navigation"], "Observed the active shell working directory with pwd.", "COMPUTING_OS") },
    { id: "identify-user", type: "event", label: "Identify the current user", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "CURRENT_USER" } }, learning: learning(["Users"], "Observed the session username with whoami.", "COMPUTING_OS") },
    { id: "inspect-groups", type: "event", label: "Inspect identity and group membership", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "IDENTITY_GROUPS" } }, learning: learning(["Users and groups"], "Observed identity, privilege, and group membership with id.", "COMPUTING_OS") },
    { id: "inspect-environment", type: "event", label: "Inspect the session environment", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "ENVIRONMENT" } }, learning: learning(["Environment variables", "Current host"], "Observed host and session context through environment variables.", "COMPUTING_OS") },
    { id: "review-ticket", type: "fact", factId: "website.ticket", label: "Read the trouble ticket", learning: learning(["Documentation", "Evidence versus assumptions"], "Read the trouble ticket and scoped the investigation to the reported hostname.", "SECURITY_REASONING") },
    { id: "query-dns-record", type: "fact", factId: "website.dnsRecordStale", label: "Query the DNS record for the reported hostname", learning: learning(["DNS", "Hosts"], "Queried the DNS record for intranet.nodeline.test directly and saw exactly what it currently resolves to.") },
    { id: "confirm-old-host-up", type: "event", label: "Confirm the current hostname target is reachable", event: { action: "PING", targetHost: "OLD-INTRANET-01" }, learning: learning(["Hosts", "IP addresses", "Reachability"], "Pinged the host that intranet.nodeline.test currently resolves to and confirmed it is up.") },
    { id: "scan-old-host", type: "fact", factId: "website.hostUpNoSite", label: "Scan the host and rule out a total outage", learning: learning(["Ports", "Services"], "Scanned the reachable host and found no web service running, ruling out a full outage.", "SECURITY_REASONING") },
    { id: "discover-migration-notice", type: "fact", factId: "website.migrationNotice", label: "Find the hostname migration notice", learning: learning(["DNS", "Hosts"], "Read the migration notice explaining the stale hostname record and the site's current location.", "SECURITY_REASONING") },
    { id: "reach-live-site", type: "fact", factId: "website.confirmedLive", label: "Reach the intranet at its current hostname", learning: learning(["DNS", "HTTP basics"], "Reached the intranet using the corrected hostname rather than the stale record, and confirmed the response.") },
  ],
  objectiveCompletion: "ALL",
  beginnerExitQuestions: [
    { id: "current-host", prompt: "What host are you operating, and what evidence establishes it?", evidenceObjectives: ["inspect-environment"] },
    { id: "dns-lookup", prompt: "What did querying the DNS record directly show you that assuming a resolution wouldn't have?", evidenceObjectives: ["query-dns-record"] },
    { id: "reachable-vs-serving", prompt: "The old hostname's target answered ping. Why didn't that mean the intranet was working?", evidenceObjectives: ["confirm-old-host-up", "scan-old-host"] },
    { id: "stale-record", prompt: "What evidence explained why intranet.nodeline.test pointed at the wrong host?", evidenceObjectives: ["discover-migration-notice"] },
    { id: "resolution", prompt: "How did you confirm the real intranet was working, rather than assuming it once you had a new hostname?", evidenceObjectives: ["reach-live-site"] },
  ],
  detections: {},
  routes: [],
  blueProfiles: [],
  defaultBlueProfile: "",
};
