import { AccessLevel, NetworkZone } from "@/app/generated/prisma/enums";
import type { ScenarioDefinition } from "./types";
import { service } from "./content";

const learning = (
  concepts: string[],
  evidence: string,
  domain: "COMPUTING_OS" | "NETWORKING" | "SECURITY_REASONING" = "NETWORKING",
): NonNullable<ScenarioDefinition["objectives"][number]["learning"]> => ({
  domain,
  concepts,
  stage: "PRACTICED",
  evidence,
});

export const wrongNetwork: ScenarioDefinition = {
  id: "wrong-network",
  name: "Wrong Network",
  organization: "Nodeline Security",
  briefing: {
    red: "The deployment team reports DEPLOY-STAGE is unreachable and assumes it is down. Determine whether the host is actually offline or whether your workstation simply has no route to it, and reach it using the documented procedure.",
    blue: "This orientation assignment has no defensive role.",
    constraints: ["Use the bounded ROOT/OS terminal", "Treat command output and local documentation as evidence", "Confirm a lack of route before assuming a host is offline"],
  },
  objectiveSummary: "Diagnose a segmented host and reach it through the documented jump host",
  presentation: { caseId: "NET-03", focus: ["Routing", "Reachability", "Segmentation"], order: 5, prerequisite: "service-unavailable" },
  availableModes: ["RED"],
  assistance: {
    guided: [
      "Try reaching DEPLOY-STAGE directly first. An unreachable result from your own workstation does not mean the host is down.",
      "Read the network access note in your home directory for how helpdesk reaches the finance deployment segment.",
      "Once on the jump host, look for a local note describing how it reaches DEPLOY-STAGE, and use the credential it documents.",
    ],
    operator: "Use the network access note as your only procedure. Confirm whether the failure is a route or a host before assuming either.",
    operatorAvailableAtStart: true,
  },
  conditions: { timeLimitMinutes: 25, minimumAvailability: 100 },
  securityControls: [{ host: "HELPDESK-01", telemetry: ["SYSTEM", "FILESYSTEM"] }, { host: "NETOPS-01", telemetry: ["AUTH", "FILESYSTEM"] }, { host: "DEPLOY-STAGE", telemetry: ["AUTH", "FILESYSTEM"] }],
  businessServices: [{ name: "Deployment staging", hosts: ["DEPLOY-STAGE"], impact: "The deployment team cannot verify the staging environment before release." }],
  persistencePolicy: { process: "helpdesk-agent", requiredPrivilege: AccessLevel.ROOT, beaconSeconds: 60 },
  knowledgeRewards: [],
  backgroundActivity: [],
  aliases: { "helpdesk-01.nodeline.test": "HELPDESK-01", "netops-01.nodeline.test": "NETOPS-01", "deploy-stage.nodeline.test": "DEPLOY-STAGE" },
  startingKnowledge: { knownHosts: ["HELPDESK-01"], knownAssets: [] },
  startingSession: { host: "HELPDESK-01", user: "trainee", path: "/home/trainee" },
  facts: [
    {
      id: "wrongnet.ticket",
      category: "NETWORK",
      known: "The deployment team reports DEPLOY-STAGE is unreachable and assumes it is offline.",
      unknown: "Whether DEPLOY-STAGE is actually down or simply not reachable from the helpdesk workstation",
      guidance: "Read the trouble ticket before touching the network.",
      discoverableFrom: "/home/trainee/TICKET-5220.txt",
      requiredFor: "Scoping the investigation correctly",
    },
    {
      id: "wrongnet.jumphostNote",
      category: "NETWORK",
      known: "The finance deployment segment is not directly reachable from general helpdesk hosts. NETOPS-01 bridges into it and is the documented path.",
      unknown: "Why direct attempts to reach DEPLOY-STAGE from HELPDESK-01 fail",
      guidance: "Read the network access note before concluding the host is down.",
      discoverableFrom: "/home/trainee/NETWORK_ACCESS.txt",
      requiredFor: "Understanding that this is a routing problem, not a host failure",
    },
    {
      id: "wrongnet.deployAccess",
      category: "IDENTITY",
      known: "NETOPS-01 keeps a documented deploy-segment credential for reaching DEPLOY-STAGE.",
      unknown: "The username and password needed to authenticate to DEPLOY-STAGE",
      guidance: "Read the deploy access note on NETOPS-01 once logged in.",
      discoverableFrom: "/home/netops/DEPLOY_ACCESS.txt",
      requiredFor: "Authenticating to DEPLOY-STAGE from the jump host",
    },
  ],
  machines: [
    {
      hostname: "HELPDESK-01",
      ip: "10.0.0.20",
      zone: NetworkZone.INTERNAL,
      os: "linux",
      users: [
        { username: "trainee", role: "operator_trainee", privilege: AccessLevel.USER, groups: ["trainees", "operations"] },
        { username: "root", role: "administrator", privilege: AccessLevel.ROOT, groups: ["root"] },
      ],
      services: [],
      files: [
        {
          path: "/home/trainee/TICKET-5220.txt",
          owner: "trainee",
          group: "trainees",
          permissions: "640",
          isSecret: false,
          contents: [
            "TICKET 5220 // DEPLOY-STAGE unreachable",
            "",
            "Reported: the deployment team cannot reach DEPLOY-STAGE and assumes it is offline.",
            "Determine whether the host is actually down or simply unreachable from your position, and record the cause with evidence.",
          ].join("\n"),
        },
        {
          path: "/home/trainee/NETWORK_ACCESS.txt",
          owner: "trainee",
          group: "trainees",
          permissions: "640",
          isSecret: false,
          contents: [
            "NETWORK OPERATIONS // Segment access",
            "",
            "The finance deployment segment is isolated from general internal hosts by design.",
            "Helpdesk workstations cannot reach DEPLOY-STAGE directly, and this is expected, not a fault.",
            "NETOPS-01 bridges into the deployment segment. Standard helpdesk access to NETOPS-01:",
            "  user: netops",
            "  password: Bridge-Access-9",
          ].join("\n"),
        },
      ],
      processes: [{ name: "sshd", pid: 130, runningAs: "root", commandLine: "/usr/sbin/sshd -D" }],
    },
    {
      hostname: "NETOPS-01",
      ip: "10.0.0.70",
      zone: NetworkZone.INTERNAL,
      os: "linux",
      users: [
        { username: "netops", role: "network_operator", privilege: AccessLevel.USER, groups: ["netops"], password: "Bridge-Access-9" },
        { username: "root", role: "administrator", privilege: AccessLevel.ROOT, groups: ["root"] },
      ],
      services: [service("ssh", 22, "root", [NetworkZone.INTERNAL])],
      files: [
        {
          path: "/home/netops/DEPLOY_ACCESS.txt",
          owner: "netops",
          group: "netops",
          permissions: "640",
          isSecret: false,
          contents: [
            "JUMP HOST // DEPLOY-STAGE access",
            "",
            "DEPLOY-STAGE is reachable only from NETOPS-01 within the finance deployment segment.",
            "Documented credential for reaching it:",
            "  user: deploy",
            "  password: Stage-Verify-7",
          ].join("\n"),
        },
      ],
      processes: [{ name: "sshd", pid: 145, runningAs: "root", commandLine: "/usr/sbin/sshd -D" }],
    },
    {
      hostname: "DEPLOY-STAGE",
      ip: "10.0.5.10",
      zone: NetworkZone.FINANCE,
      os: "linux",
      users: [
        { username: "deploy", role: "deploy_operator", privilege: AccessLevel.USER, groups: ["deploy"], password: "Stage-Verify-7" },
        { username: "root", role: "administrator", privilege: AccessLevel.ROOT, groups: ["root"] },
      ],
      services: [service("ssh", 22, "root", [NetworkZone.FINANCE])],
      files: [
        {
          path: "/srv/deploy/STAGE_HEALTHCHECK.txt",
          owner: "deploy",
          group: "deploy",
          permissions: "640",
          isSecret: false,
          contents: "STAGE_HEALTHCHECK: DEPLOY-STAGE online, all services nominal. Never actually offline; unreachable only from outside the deployment segment.",
        },
      ],
      processes: [{ name: "sshd", pid: 150, runningAs: "root", commandLine: "/usr/sbin/sshd -D" }],
    },
  ],
  connections: [
    { source: "HELPDESK-01", target: "NETOPS-01", port: 22 },
    { source: "NETOPS-01", target: "DEPLOY-STAGE", port: 22 },
  ],
  discoveries: [
    { trigger: { kind: "file", host: "HELPDESK-01", value: "/home/trainee/TICKET-5220.txt" }, facts: ["wrongnet.ticket"] },
    { trigger: { kind: "file", host: "HELPDESK-01", value: "/home/trainee/NETWORK_ACCESS.txt" }, hosts: ["NETOPS-01"], facts: ["wrongnet.jumphostNote"], credentials: [{ username: "netops", scope: "NETOPS-01" }] },
    { trigger: { kind: "file", host: "NETOPS-01", value: "/home/netops/DEPLOY_ACCESS.txt" }, hosts: ["DEPLOY-STAGE"], facts: ["wrongnet.deployAccess"], credentials: [{ username: "deploy", scope: "DEPLOY-STAGE" }] },
  ],
  objectives: [
    { id: "locate-session", type: "event", label: "Establish the current directory", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "CURRENT_DIRECTORY" } }, learning: learning(["Files and directories", "Command-line navigation"], "Observed the active shell working directory with pwd.", "COMPUTING_OS") },
    { id: "identify-user", type: "event", label: "Identify the current user", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "CURRENT_USER" } }, learning: learning(["Users"], "Observed the session username with whoami.", "COMPUTING_OS") },
    { id: "inspect-groups", type: "event", label: "Inspect identity and group membership", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "IDENTITY_GROUPS" } }, learning: learning(["Users and groups"], "Observed identity, privilege, and group membership with id.", "COMPUTING_OS") },
    { id: "inspect-environment", type: "event", label: "Inspect the session environment", event: { action: "OBSERVATION_RECORDED", targetHost: "HELPDESK-01", metadata: { kind: "ENVIRONMENT" } }, learning: learning(["Environment variables", "Current host"], "Observed host and session context through environment variables.", "COMPUTING_OS") },
    { id: "review-ticket", type: "fact", factId: "wrongnet.ticket", label: "Read the trouble ticket", learning: learning(["Documentation", "Evidence versus assumptions"], "Read the trouble ticket and scoped the investigation before assuming the host was down.", "SECURITY_REASONING") },
    { id: "discover-jumphost", type: "fact", factId: "wrongnet.jumphostNote", label: "Find the documented network segmentation and jump host", learning: learning(["Routing", "Segmentation"], "Identified that the deployment segment is intentionally isolated and requires a jump host, rather than assuming a fault.", "SECURITY_REASONING") },
    { id: "reach-netops", type: "event", label: "Reach the jump host", event: { action: "SESSION_CREATED", targetHost: "NETOPS-01", userId: "netops" }, learning: learning(["SSH", "Reachability"], "Authenticated to NETOPS-01 using the documented bridge credential.") },
    { id: "discover-deploy-access", type: "fact", factId: "wrongnet.deployAccess", label: "Find the documented deploy-segment credential", learning: learning(["Users", "Documentation"], "Identified the documented credential for reaching DEPLOY-STAGE from the jump host.", "SECURITY_REASONING") },
    { id: "reach-deploy-stage", type: "event", label: "Reach DEPLOY-STAGE from the jump host", event: { action: "SESSION_CREATED", targetHost: "DEPLOY-STAGE", userId: "deploy" }, learning: learning(["Routing", "Segmentation", "SSH"], "Reached DEPLOY-STAGE through the documented jump host after confirming the segment boundary, not by bypassing it.") },
    { id: "retrieve-healthcheck", type: "retrieve_file", host: "DEPLOY-STAGE", path: "/srv/deploy/STAGE_HEALTHCHECK.txt", label: "Retrieve STAGE_HEALTHCHECK.txt", learning: learning(["Evidence versus assumptions"], "Retrieved confirmation that DEPLOY-STAGE was healthy the entire time and only unreachable from outside its segment.", "SECURITY_REASONING") },
  ],
  objectiveCompletion: "ALL",
  beginnerExitQuestions: [
    { id: "current-host", prompt: "What host are you operating, and what evidence establishes it?", evidenceObjectives: ["inspect-environment"] },
    { id: "route-vs-down", prompt: "Why did DEPLOY-STAGE being unreachable from HELPDESK-01 not mean it was offline?", evidenceObjectives: ["discover-jumphost"] },
    { id: "path", prompt: "What path did you take to reach DEPLOY-STAGE, and what documented each hop of it?", evidenceObjectives: ["reach-netops", "discover-deploy-access", "reach-deploy-stage"] },
    { id: "evidence-outcome", prompt: "What confirms DEPLOY-STAGE was healthy the whole time?", evidenceObjectives: ["retrieve-healthcheck"] },
  ],
  detections: {},
  routes: [],
  blueProfiles: [],
  defaultBlueProfile: "",
};
